<?php 
/*
 Generated by Manuigniter v2.0 
 www.manuigniter.com
*/
class Attendance_leave extends CI_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Attendance_leave_model');
 } 
 /*
* Listing of attendance_leave
 */
public function index()
{
  try{
      $data['noof_page'] = 0;
     $data['attendance_leave'] = $this->Attendance_leave_model->get_all_attendance_leave();
      $data['_view'] = 'attendance_leave/index';
      $this->load->view('layouts/main',$data);
    } catch (Exception $ex) {
      throw new Exception('Attendance_leave Controller : Error in index function - ' . $ex);
  }  
}
 /*
  * Adding a new attendance_leave
  */
 function add()
 {  
try{
      $params = array(
       'user_id'=> $this->input->post('user_id'),
       'user_type'=> $this->input->post('user_type'),
       'leaveDate'=> $this->input->post('leaveDate'),
       'leave_reasons'=> $this->input->post('leave_reasons'),
       'status'=> $this->input->post('status'),
       'screen_by'=> $this->input->post('screen_by'),
       'remarks'=> $this->input->post('remarks'),
       'created_by'=> $this->input->post('created_by'),
       'created_at'=> $this->input->post('created_at'),
       'modified_by'=> $this->input->post('modified_by'),
       'modified_at'=> $this->input->post('modified_at'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       if(isset($_POST) && count($_POST) > 0)     
        {  
            $leaveID= $this->Attendance_leave_model->add_attendance_leave($params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully added.</div>');
              redirect('attendance_leave/index');
        }
        else
        { 
           $data['_view'] = 'attendance_leave/add';
            $this->load->view('layouts/main',$data);
        }
  } catch (Exception $ex) {
    throw new Exception('Attendance_leave Controller : Error in add function - ' . $ex);
  }  
 }  
  /*
  * Editing a attendance_leave
 */
 public function edit($leaveID)
 {   
  try{
   $data['attendance_leave'] = $this->Attendance_leave_model->get_attendance_leave($leaveID);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['attendance_leave']['leaveID']))
      {
        $params = array(
           'user_id'=> $this->input->post('user_id'),
           'user_type'=> $this->input->post('user_type'),
           'leaveDate'=> $this->input->post('leaveDate'),
           'leave_reasons'=> $this->input->post('leave_reasons'),
           'status'=> $this->input->post('status'),
           'screen_by'=> $this->input->post('screen_by'),
           'remarks'=> $this->input->post('remarks'),
           'created_by'=> $this->input->post('created_by'),
           'created_at'=> $this->input->post('created_at'),
           'modified_by'=> $this->input->post('modified_by'),
           'modified_at'=> $this->input->post('modified_at'),
        );
          if(isset($_POST) && count($_POST) > 0)     
           {  
           $this->Attendance_leave_model->update_attendance_leave($leaveID,$params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully updated.</div>');
                redirect('attendance_leave/index');
           }
           else
          {
              $data['_view'] = 'attendance_leave/edit';
              $this->load->view('layouts/main',$data);
          }
  }
  else
  show_error('The attendance_leave you are trying to edit does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Attendance_leave Controller : Error in edit function - ' . $ex);
  }  
} 
/*
  * Deleting attendance_leave
  */
  function remove($leaveID)
   {
    try{
      $attendance_leave = $this->Attendance_leave_model->get_attendance_leave($leaveID);
  // check if the attendance_leave exists before trying to delete it
       if(isset($attendance_leave['leaveID']))
       {
         $this->Attendance_leave_model->delete_attendance_leave($leaveID);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully Removed.</div>');
           redirect('attendance_leave/index');
       }
       else
       show_error('The attendance_leave you are trying to delete does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Attendance_leave Controller : Error in remove function - ' . $ex);
  }  
  }
  /*
  * View more a attendance_leave
 */
 public function view_more($leaveID)
 {   
try{
   $data['attendance_leave'] = $this->Attendance_leave_model->get_attendance_leave($leaveID);
     if(isset($data['attendance_leave']['leaveID']))
      {
              $data['_view'] = 'attendance_leave/view_more';
              $this->load->view('layouts/main',$data);
      }
      else
        show_error('The attendance_leave you are trying to view more does not exist.');
    } catch (Exception $ex) {
    throw new Exception('Attendance_leave Controller : Error in View more function - ' . $ex);
  }  
} 
 /*
* Listing of attendance_leave
 */
public function search_by_clm()
{
    $column_name= $this->input->post('column_name');
    $value_id= $this->input->post('value_id');
     $data['noof_page'] = 0;
     $params = array();
    $data['attendance_leave'] = $this->Attendance_leave_model->get_all_attendance_leave_by_cat($column_name,$value_id);
      $data['_view'] = 'attendance_leave/index';
      $this->load->view('layouts/main',$data);
}
 /*
* get search values by column- attendance_leave
 */
public function get_search_values_by_clm()
{
    $clm_name= $this->input->post('clm_name');
    $value= $this->input->post('value');
    $id= $this->input->post('id');
        $params = array(
        $clm_name=>$value,
        );
           $this->Attendance_leave_model->update_attendance_leave($id,$params);
   $data['noof_page'] = 0;
  $data['attendance_leave'] = $this->Attendance_leave_model->get_all_attendance_leave();
  $this->load->view('attendance_leave/index',$data);
}
 }
