<?php 
/*
 Generated by Manuigniter v2.0 
 www.manuigniter.com
*/
class Attendance_holidays extends CI_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Attendance_holidays_model');
 } 
  /*
  * Listing of attendance_holidays
  */
  public function index()
  {
    try{
        $data['noof_page'] = 0;

        $this->load->model('Academic_year_model');
        $data['academic_year_data'] = $this->Academic_year_model->check_active_session();
        $session_id = $data['academic_year_data']['session_id'];

        $data['attendance_holidays'] = $this->Attendance_holidays_model->get_all_attendance_holidays($session_id);
        $data['_view'] = 'attendance_holidays/index';
        $this->load->view('layouts/main',$data);
      } catch (Exception $ex) {
        throw new Exception('Attendance_holidays Controller : Error in index function - ' . $ex);
    }  
  }
 /*
  * Adding a new attendance_holidays
  */
 function add()
 {  
  try{
      if(isset($_POST) && count($_POST) > 0)     
      {  

        $this->load->model('Academic_year_model');
        $data['academic_year_data'] = $this->Academic_year_model->check_active_session();
        $session_id = $data['academic_year_data']['session_id'];

        $params = array(
          'holiday'=> $this->input->post('holiday'),
          'holidayDate'=> $this->input->post('holidayDate'),
          'session_id' => $session_id,
          'statusID'=> 1,
          'created_by'=> $this->session->user_id,
        );
        $holidayID= $this->Attendance_holidays_model->add_attendance_holidays($params);
        $this->session->set_flashdata('alertType','success' );
        $this->session->set_flashdata('message','Holiday Added Successfully.' );
        redirect('attendance_holidays/index');
      }
      else
      { 
          $data['_view'] = 'attendance_holidays/add';
          $this->load->view('layouts/main',$data);
      }
    } catch (Exception $ex) {
      throw new Exception('Attendance_holidays Controller : Error in add function - ' . $ex);
    }  
 }  
  /*
  * Editing a attendance_holidays
 */
 public function edit($holidayID)
 {   
  try{
    $data['attendance_holidays'] = $this->Attendance_holidays_model->get_attendance_holidays($holidayID);
    if(isset($data['attendance_holidays']['holidayID']))
    {
      $params = array(
        'holiday'=> $this->input->post('holiday'),
        'holidayDate'=> $this->input->post('holidayDate'),
        'modified_by'=> $this->session->user_id,
      );
      if(isset($_POST) && count($_POST) > 0)     
      {  
        $this->Attendance_holidays_model->update_attendance_holidays($holidayID,$params);
        $this->session->set_flashdata('alertType','success' );
        $this->session->set_flashdata('message','Holiday Updated Successfully.' );
        redirect('attendance_holidays/index');
      }
      else
      {
        $data['_view'] = 'attendance_holidays/edit';
        $this->load->view('layouts/main',$data);
      }
    }
    else
    show_error('The attendance_holidays you are trying to edit does not exist.');
    } catch (Exception $ex) {
      throw new Exception('Attendance_holidays Controller : Error in edit function - ' . $ex);
    }  
  } 
  /*
  * Deleting attendance_holidays
  */
  function remove($holidayID)
   {
    try
    {
      $attendance_holidays = $this->Attendance_holidays_model->get_attendance_holidays($holidayID);
      // check if the attendance_holidays exists before trying to delete it
       if(isset($attendance_holidays['holidayID']))
       {
          $params = array(
            'statusID'=> 3,
            'modified_by'=> $this->session->user_id,
          );
         $this->Attendance_holidays_model->update_attendance_holidays($holidayID,$params);
         $this->session->set_flashdata('alertType','success' );
         $this->session->set_flashdata('message','Holiday Deleted Successfully.' );
         redirect('attendance_holidays/index');
       }
       else
       show_error('The attendance_holidays you are trying to delete does not exist.');
    } catch (Exception $ex) {
      throw new Exception('Attendance_holidays Controller : Error in remove function - ' . $ex);
    }  
  }

}
