<?php

/*
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Gallery extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Gallery_model');
    }

    /*
     * Listing of gallery
     */

    function index() {
        $data['gallery'] = $this->Gallery_model->get_all_gallery();

        $data['_view'] = 'gallery/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new gallery
     */

    function add() {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('title', 'Title', 'required');
        $this->form_validation->set_rules('description', 'Description', 'required');
        $this->form_validation->set_rules('show_image', 'Show Image', 'required');

        if ($this->form_validation->run()) {
//            var_dump($_FILES['image']);
//            die;
            //images which have to upload


            $filecount = count($_FILES['image']['name']);
            for ($i = 0; $i < $filecount; $i++) {
                $_FILES['mediaelement']['name'] = $_FILES['image']['name'][$i];
                $_FILES['mediaelement']['type'] = $_FILES['image']['type'][$i];
                $_FILES['mediaelement']['tmp_name'] = $_FILES['image']['tmp_name'][$i];
                $_FILES['mediaelement']['error'] = $_FILES['image']['error'][$i];
                $_FILES['mediaelement']['size'] = $_FILES['image']['size'][$i];
                
                
                $config['upload_path'] = './uploads/gallery/';
                $config['allowed_types'] = 'gif|jpg|png';
                $this->load->library('upload', $config);
                $this->upload->initialize($config);
                $this->upload->do_upload('mediaelement');
                $images[] = $this->upload->data()['file_name'];
            }
            
           

            //end images which have to upload
//            if (!$this->upload->do_upload('image')) {
//                $error = array('error' => $this->upload->display_errors());
//                $image = '';
//            } else {
//                $upload_data = $this->upload->data(); //Returns array of containing all of the data related to the file you uploaded.
//                $image = $upload_data['file_name'];
//            }


            $params = array(
                'title' => $this->input->post('title'),
                'description' => $this->input->post('description'),
                'image' => json_encode($images),
                'show_image' => $this->input->post('show_image'),
            );
            
            

            $gallery_id = $this->Gallery_model->add_gallery($params);
            redirect('gallery/index');
        } else {
            $data['_view'] = 'gallery/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a gallery
     */

    function edit($id) {
        // check if the gallery exists before trying to edit it
        $data['gallery'] = $this->Gallery_model->get_gallery($id);

        if (isset($data['gallery']['id'])) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('title', 'Title', 'required');
            $this->form_validation->set_rules('description', 'Description', 'required');
            $this->form_validation->set_rules('show_image', 'Show Image', 'required');

            if ($this->form_validation->run()) {
                $config['upload_path'] = './uploads/gallery/';
                $config['allowed_types'] = 'gif|jpg|png';
                $this->load->library('upload', $config);

                if (!$this->upload->do_upload('image')) {
                    $error = array('error' => $this->upload->display_errors());
                    $image = '';
                } else {
                    $upload_data = $this->upload->data(); //Returns array of containing all of the data related to the file you uploaded.
                    $image = $upload_data['file_name'];
                }

                if ($image == '') {
                    $image = $this->input->post('old_image');
                }
                $params = array(
                    'title' => $this->input->post('title'),
                    'description' => $this->input->post('description'),
                    'image' => $image,
                    'show_image' => $this->input->post('show_image'),
                );

                $this->Gallery_model->update_gallery($id, $params);
                redirect('gallery/index');
            } else {
                $data['_view'] = 'gallery/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The gallery you are trying to edit does not exist.');
    }

    /*
     * Deleting gallery
     */

    function remove($id) {
        $gallery = $this->Gallery_model->get_gallery($id);

        // check if the gallery exists before trying to delete it
        if (isset($gallery['id'])) {
            $this->Gallery_model->delete_gallery($id);
            redirect('gallery/index');
        } else
            show_error('The gallery you are trying to delete does not exist.');
    }

}
