<?php

/*
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Leaving_certificate extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Leaving_certificate_model');
        $this->load->model('Student_model');
        $this->load->model('Clas_model');
        $this->load->model('Payment_model');
    }

    /*
     * Listing of leaving_certificate
     */

    function index() {
        $data['leaving_certificate'] = $this->Leaving_certificate_model->get_all_leaving_certificate();
        //print_r($data);
        //die;
        $data['_view'] = 'leaving/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new leaving_certificate
     */

    function add() {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('fullname', 'Full Name', 'required');
        $this->form_validation->set_rules('father_name', 'Father Name', 'required');
        $this->form_validation->set_rules('mother_name', 'Mother Name', 'required');
        $this->form_validation->set_rules('surname', 'Surname', 'required');
        $this->form_validation->set_rules('b_tah', 'Birth Place Tahsil');
        $this->form_validation->set_rules('b_dist', 'Birth Place District');
        $this->form_validation->set_rules('b_state', 'Birth Place State');
        $this->form_validation->set_rules('b_country', 'Birth Place Country');
        $this->form_validation->set_rules('saral_id', 'Saral Id', 'required');
        $this->form_validation->set_rules('progress', 'Progress', 'required');
        $this->form_validation->set_rules('reason', 'Reason', 'required');
        $this->form_validation->set_rules('remark', 'Remark', 'required');
        $this->form_validation->set_rules('student_id', 'Student Id', 'required');
        $this->form_validation->set_rules('place_of_birth', 'Place Of Birth','required');
        $this->form_validation->set_rules('studying_from_class', 'Studying From Class ','required');
        $this->form_validation->set_rules('sought_admission_in_class', 'Class Of Addmission','required');


        if ($this->form_validation->run()) {
            //remaining payment check
            $unpaidPayments = $this->Payment_model->get_unpaid_payments($this->input->post('student_id'));
            //$unpaidOldPayment = $this->Payment_model->get_unpaied_old_payment($this->input->post('student_id'));
            if(!empty($unpaidPayments)){
                $this->session->set_flashdata('alertType','failed' );
                $this->session->set_flashdata('message','Student has Outstanding Payment Plz Clear Fees first ...' );
                redirect('leaving_certificate/index');
            }
            $date_of_leave = strtr($this->input->post('date_of_leave'), '/', '-');
            $date_of_issue = strtr($this->input->post('date_of_issue'), '/', '-');
            $params = array(
                'student_id' => $this->input->post('student_id'),
                'fullname' => $this->input->post('fullname'),
                'father_name' => $this->input->post('father_name'),
                'mother_name' => $this->input->post('mother_name'),
                'surname' => $this->input->post('surname'),
                'b_tah' => $this->input->post('b_tah'),
                'b_dist' => $this->input->post('b_dist'),
                'b_state' => $this->input->post('b_state'),
                'b_country' => $this->input->post('b_country'),
                'progress' => $this->input->post('progress'),
                'reason' => $this->input->post('reason'),
                'remark' => $this->input->post('remark'),
                'academic_year' => $this->input->post('academic_year'),
                'date_of_leave' => date('Y-m-d', strtotime($date_of_leave)),
                'date_of_issueing' => date('Y-m-d', strtotime($date_of_issue)),
                'studying_since' => $this->input->post('studying_since'),
                'studying_from_class'=>$this->input->post('studying_from_class'),
                'created_date' => date('Y-m-d'),
            );

            $leaving_certificate_id = $this->Leaving_certificate_model->add_leaving_certificate($params);
            $student_param = array(
                'is_active' => 0,
                'caste' => $this->input->post('caste'),
                'religion' => $this->input->post('religion'),
            );
            $this->Student_model->update_student($this->input->post('student_id'), $student_param);
            redirect('leaving_certificate/index');
        } else {

            $this->load->model('Clas_model');
            $data['all_class'] = $this->Clas_model->get_all_class();

            $data['_view'] = 'leaving/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a leaving_certificate
     */

    function edit($leaving_id) {
        // check if the leaving_certificate exists before trying to edit it
        $data['leaving_certificate'] = $this->Leaving_certificate_model->get_leaving_certificate($leaving_id);
        if (isset($data['leaving_certificate']['leaving_id'])) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('fullname', ' Fullname', 'required');
            $this->form_validation->set_rules('father_name', 'Father Name', 'required');
            $this->form_validation->set_rules('mother_name', 'Mother Name', 'required');
            $this->form_validation->set_rules('surname', 'Surname');
//            $this->form_validation->set_rules('b_tah', 'B Tah');
//            $this->form_validation->set_rules('b_dist', 'B Dist');
//            $this->form_validation->set_rules('b_state', 'B State', 'required');
//            $this->form_validation->set_rules('b_country', 'B Country', 'required');
            $this->form_validation->set_rules('progress', 'Progress', 'required');
            $this->form_validation->set_rules('reason', 'Reason', 'required');
            $this->form_validation->set_rules('remark', 'Remark', 'required');
            $this->form_validation->set_rules('saral_id', 'Saral Id', 'required');
            $this->form_validation->set_rules('student_id', 'Student Id', 'required');
            $this->form_validation->set_rules('place_of_birth', 'Place Of Birth','required');
            $this->form_validation->set_rules('studying_from_class', 'Studying From Class ','required');
            $this->form_validation->set_rules('registration_no', 'GR NO ','required');
            $this->form_validation->set_rules('sought_admission_in_class', 'Class Of Addmission','required');

            if ($this->form_validation->run()) {
                $date_of_leave = strtr($this->input->post('date_of_leave'), '/', '-');
                $date_of_issue = strtr($this->input->post('date_of_issue'), '/', '-');
                $params = array(
                    'student_id' => $this->input->post('student_id'),
                    'fullname' => $this->input->post('fullname'),
                    'father_name' => $this->input->post('father_name'),
                    'mother_name' => $this->input->post('mother_name'),
                    'surname' => $this->input->post('surname'),
                    'b_tah' => $this->input->post('b_tah'),
                    'b_dist' => $this->input->post('b_dist'),
                    'b_state' => $this->input->post('b_state'),
                    'b_country' => $this->input->post('b_country'),
                    'progress' => $this->input->post('progress'),
                    'reason' => $this->input->post('reason'),
                    'remark' => $this->input->post('remark'),
                    'academic_year' => $this->input->post('academic_year'),
                    'date_of_leave' => date('Y-m-d', strtotime($date_of_leave)),
                    'date_of_issueing' => date('Y-m-d', strtotime($date_of_issue)),
                    'studying_since' => $this->input->post('studying_since'),
                    'studying_from_class'=>$this->input->post('studying_from_class'),
                );

                $this->Leaving_certificate_model->update_leaving_certificate($leaving_id, $params);
                $student_id = $this->input->post('student_id');
                $student_params = array(
                    'registration_no'=>$this->input->post('registration_no'),
                    'aadhar_no'=>$this->input->post('aadhar_no'),
                    'saral_id'=>$this->input->post('saral_id'),
                    'father_name' => $this->input->post('father_name'),
                    'sought_admission_in_class' => $this->input->post('sought_admission_in_class'),
                    'nationality'=>$this->input->post('nationality'),
                    'mother_tounge'=>$this->input->post('mother_tounge'),
                    'religion'=>$this->input->post('religion'),
                    'caste'=>$this->input->post('caste'),
                    'category'=>$this->input->post('category'),
                    'dob'=>date('Y-m-d',strtotime(strtr($this->input->post('dob'),'/','-'))),
                    'place_of_birth'=>$this->input->post('place_of_birth'),
                    'last_school'=>$this->input->post('last_school'),
                    'last_school'=>$this->input->post('last_school'),
                    'register_date'=>date('Y-m-d',strtotime(strtr($this->input->post('register_date'),'/','-'))),
                );
                $this->Leaving_certificate_model->updateStudent($student_id,$student_params);
                redirect('leaving_certificate/index');
            } else {
                $this->load->model('Student_model');
                $data['all_student'] = $this->Student_model->get_all_student();

                $data['_view'] = 'leaving/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The leaving_certificate you are trying to edit does not exist.');
    }

    /*
     * Deleting leaving_certificate
     */

    function remove($leaving_id) {

        $leaving_certificate = $this->Leaving_certificate_model->get_leaving_certificate($leaving_id);

        // check if the leaving_certificate exists before trying to delete it
        if (isset($leaving_certificate['leaving_id'])) {
            $this->Leaving_certificate_model->delete_leaving_certificate($leaving_id);
            redirect('leaving_certificate/index');
        } else
            show_error('The leaving_certificate you are trying to delete does not exist.');
    }

    function view($leaving_id) {
        $data['leaving_certificate'] = $this->Leaving_certificate_model->get_leaving_certificate($leaving_id);
        $data['student'] = $this->Student_model->getStudentData($data['leaving_certificate']['student_id']);
        $data['class'] = $this->Clas_model->get_clas($data['leaving_certificate']['class_id']);

        //echo "<pre>";
        //var_dump($data);die;
        $data['_view'] = 'leaving/view';
        $this->load->view('layouts/main', $data);
    }

    function duplicate($leaving_id) {
        $data = $this->Leaving_certificate_model->get_leaving_certificate($leaving_id);
        $params = array(
            'student_id' => $data['student_id'],
            'fullname' => $data['fullname'],
            'father_name' => $data['father_name'],
            'mother_name' => $data['mother_name'],
            'surname' => $data['surname'],
            'b_tah' => $data['b_tah'],
            'b_dist' => $data['b_dist'],
            'b_state' => $data['b_state'],
            'b_country' => $data['b_country'],
            'progress' => $data['progress'],
            'reason' => $data['reason'],
            'remark' => $data['remark'],
            'academic_year' => $data['academic_year'],
            'date_of_leave' => $data['date_of_leave'],
            'date_of_issueing' => $data['date_of_issueing'],
            'studying_since' => $data['studying_since'],
            'studying_from_class'=> $data['studying_from_class'],
            'created_date' => date('Y-m-d'),
            'is_dl' => TRUE,
        );
        $leaving_certificate_id = $this->Leaving_certificate_model->add_leaving_certificate($params);
        $dliving = array(
            'dleaving_id' => $leaving_certificate_id,
        );
        $this->Leaving_certificate_model->update_dl($leaving_id, $dliving);
        redirect('leaving_certificate/index');
        //$data['leaving_id'] = '405';
        //print_r($tata);
        //die;
        //$data['student'] = $this->Student_model->getStudentData($data['leaving_certificate']['student_id']);
        //$data['class'] = $this->Clas_model->get_clas($data['leaving_certificate']['class_id']);

        // echo "<pre>";
        // var_dump($data);die;
        //$data['_view'] = 'leaving/view';
        //$this->load->view('layouts/main', $data);
    }

    function triplicate($leaving_id) {
        $data = $this->Leaving_certificate_model->get_leaving_certificate($leaving_id);
        $params = array(
            'student_id' => $data['student_id'],
            'fullname' => $data['fullname'],
            'father_name' => $data['father_name'],
            'mother_name' => $data['mother_name'],
            'surname' => $data['surname'],
            'b_tah' => $data['b_tah'],
            'b_dist' => $data['b_dist'],
            'b_state' => $data['b_state'],
            'b_country' => $data['b_country'],
            'progress' => $data['progress'],
            'reason' => $data['reason'],
            'remark' => $data['remark'],
            'academic_year' => $data['academic_year'],
            'date_of_leave' => $data['date_of_leave'],
            'date_of_issueing' => $data['date_of_issueing'],
            'studying_since' => $data['studying_since'],
            'studying_from_class'=>$data['studying_from_class'],
            'created_date' => date('Y-m-d'),
            'is_tl' => TRUE,
            
        );
        $leaving_certificate_id = $this->Leaving_certificate_model->add_leaving_certificate($params);
        $dliving = array(
            'tleaving_id' => $leaving_certificate_id,
        );
        $this->Leaving_certificate_model->update_dl($leaving_id, $dliving);
        redirect('leaving_certificate/index');
        //$data['leaving_id'] = '405';
        //print_r($tata);
        //die;
        //$data['student'] = $this->Student_model->getStudentData($data['leaving_certificate']['student_id']);
        //$data['class'] = $this->Clas_model->get_clas($data['leaving_certificate']['class_id']);

        // echo "<pre>";
        // var_dump($data);die;
        //$data['_view'] = 'leaving/view';
        //$this->load->view('layouts/main', $data);
    }


}
