<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Management extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Management_model');
    } 

    /*
     * Listing of management
     */
    function index()
    {
        $data['management'] = $this->Management_model->get_all_management();
        
        $data['_view'] = 'management/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new management
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','required');
		$this->form_validation->set_rules('designation','Designation','required');
//		$this->form_validation->set_rules('mobile_no','Mobile No','required');
		
		if($this->form_validation->run())     
        {   
                     $config['upload_path'] = './uploads/management/';
            $config['allowed_types'] = 'gif|jpg|png|jpeg';
            $this->load->library('upload', $config);

            if (!$this->upload->do_upload('image')) {
                $error = array('error' => $this->upload->display_errors());
                $image = '';
            } else {
                $upload_data = $this->upload->data(); //Returns array of containing all of the data related to the file you uploaded.
                $image_data = $upload_data;
                $image = $upload_data['file_name'];
                $this->load->library('image_lib');
                $configer = array(
                    'image_library' => 'gd2',
                    'source_image' => $image_data['full_path'],
                    'maintain_ratio' => TRUE,
                    'width' => 200,
                    'height' => 200,
                );
                $this->image_lib->clear();
                $this->image_lib->initialize($configer);
                $this->image_lib->resize();
            }
            $params = array(
				'name' => $this->input->post('name'),
				'designation' => $this->input->post('designation'),
				'mobile_no' => $this->input->post('mobile_no'),
				'image' => $image,
            );
            
            $management_id = $this->Management_model->add_management($params);
            redirect('management/index');
        } else {
            $data['_view'] = 'management/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a management
     */
    function edit($id)
    {   
        // check if the management exists before trying to edit it
        $data['management'] = $this->Management_model->get_management($id);
        
        if(isset($data['management']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Name','required');
			$this->form_validation->set_rules('designation','Designation','required');
			$this->form_validation->set_rules('mobile_no','Mobile No','required');
		
			if($this->form_validation->run())     
            {   
                             $config['upload_path'] = './uploads/management/';
                $config['allowed_types'] = 'gif|jpg|png';
                $this->load->library('upload', $config);

                if (!$this->upload->do_upload('image')) {
                    $error = array('error' => $this->upload->display_errors());
                    $image = '';
                } else {
                    $upload_data = $this->upload->data(); //Returns array of containing all of the data related to the file you uploaded.
                    $image = $upload_data['file_name'];
                }

                if ($image == '') {
                    $image = $this->input->post('old_image');
                }
                $params = array(
					'name' => $this->input->post('name'),
					'designation' => $this->input->post('designation'),
					'mobile_no' => $this->input->post('mobile_no'),
					'image' =>$image,
                );

                $this->Management_model->update_management($id,$params);            
                redirect('management/index');
            }
            else
            {
                $data['_view'] = 'management/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The management you are trying to edit does not exist.');
    } 

    /*
     * Deleting management
     */
    function remove($id)
    {
        $management = $this->Management_model->get_management($id);

        // check if the management exists before trying to delete it
        if(isset($management['id']))
        {
            $this->Management_model->delete_management($id);
            redirect('management/index');
        }
        else
            show_error('The management you are trying to delete does not exist.');
    }
    
}
