<?php

/*
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Student extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Student_model');
        $this->load->model('Clas_model');
        $this->load->model('Section_model');
        $this->load->model('Fee_model');
        $this->load->model('Payment_model');
        $this->load->model('Academic_year_model');
        $this->load->model('Payment_log_model');
    }

    /*
     * Listing of student
     */

    function index() {
        $data['student'] = $this->Student_model->get_all_student();

        $data['_view'] = 'student/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new student
     */

    function add() {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('fullname', 'Fullname', 'required');
        $this->form_validation->set_rules('class_id', 'Class Id', 'required');
        $this->form_validation->set_rules('section_id', 'Section Id', 'required');
        $this->form_validation->set_rules('place_of_birth', 'Place Of Birth', 'required');
        $this->form_validation->set_rules('dob', 'Dob', 'required');
        $this->form_validation->set_rules('gender', 'gender', 'required');
        $this->form_validation->set_rules('religion', 'Religion', 'required');
        $this->form_validation->set_rules('nationality', 'Nationality', 'required');
       // $this->form_validation->set_rules('nationality', 'Nationality', 'required');
        $this->form_validation->set_rules('mother_tounge', 'Mother  Tounge', 'required');
        $this->form_validation->set_rules('caste', 'Caste', 'required');
        $this->form_validation->set_rules('category', 'Category', 'required');
        $this->form_validation->set_rules('father_name', 'Father Name', 'required');
        $this->form_validation->set_rules('aadhar_no', 'Aadhar No', 'min_length[12]|max_length[12]');
        $this->form_validation->set_rules('mobile_no', 'Mobile No', 'required');
        $this->form_validation->set_rules('mother_full_name', 'Mother Full Name', 'required');

        if ($this->form_validation->run()) {

            if (isset($_POST['rte_applicable'])) {
                $rte_applicable = 1;
            } else {
                $rte_applicable = 0;
            }
            $config['upload_path'] = './uploads/student/';
            $config['allowed_types'] = 'gif|jpg|png';
            $this->load->library('upload', $config);

            if (!$this->upload->do_upload('image')) {
                $error = array('error' => $this->upload->display_errors());
                $image = '';
            } else {
                $upload_data = $this->upload->data(); //Returns array of containing all of the data related to the file you uploaded.
                $image = $upload_data['file_name'];
            }
            //  var_dump($this->input->post());die;
            $parent_on_service = $this->input->post('parent_on_service');
            $last_school_is_recognize = $this->input->post('is_last_school_recognize');

            $currentSessionData = $this->Academic_year_model->check_active_session(); //arr
            //print_r($data['current_session_data']);die();
            if(empty($currentSessionData)){
                $this->session->set_flashdata('alertType','failed' );
                $this->session->set_flashdata('message','No session set as active. plz make current session as active' );
                redirect('student/add');
            }

            $params = array(
                'class_id' => $this->input->post('class_id'),
                'section_id' => $this->input->post('section_id'),
                'rte_applicable' => $rte_applicable,
                'register_date' => $this->input->post('admission_date'), //date('Y-d-m', strtotime($this->input->post('admission_date'))),
                'registration_no' => $this->input->post('registration_no'),
                'saral_id' => $this->input->post('saral_id'),
                'fullname' => $this->input->post('fullname'),
                'aadhar_no' => $this->input->post('aadhar_no'),
                'gender' => $this->input->post('gender'),
                'religion' => $this->input->post('religion'),
                'nationality' => $this->input->post('nationality'),
                'mother_tounge' => $this->input->post('mother_tounge'),
                'caste' => $this->input->post('caste'),
                'category' => $this->input->post('category'),
                'age' => $this->input->post('age'),
                'dob' => $this->input->post('dob'),//date('Y-d-m', strtotime($this->input->post('dob'))),
                'last_school' => $this->input->post('last_school'),
                'last_class' => $this->input->post('last_class'),
                'last_medium' => $this->input->post('last_medium'),
                'parent_on_service' => !isset($parent_on_service) ? 0 : 1,
                'is_last_school_recognize' => !isset($last_school_is_recognize) ? 0 : 1,
                'father_name' => $this->input->post('father_name'),
                'at_post' => $this->input->post('at_post'),
                'tahsil' => $this->input->post('tahsil'),
                'dist' => $this->input->post('dist'),
                'occupation' => $this->input->post('occupation'),
                'ph_no' => $this->input->post('ph_no'),
                'mobile_no' => $this->input->post('mobile_no'),
                'office_address_phone_no' => $this->input->post('office_address_phone_no'),
                'mother_full_name' => $this->input->post('mother_full_name'),
                'annual_income' => $this->input->post('annual_income'),
                'local_address' => $this->input->post('local_address'),
                'relation_ship_with_parent' => $this->input->post('relation_ship_with_parent'),
                'academic_year' => $currentSessionData['session'],
                'place_of_birth' => $this->input->post('place_of_birth'),
                'session_id' => $currentSessionData['session_id'],
                'image' => $image,
                'created_by'=> $this->session->user_id,
                'old_fees' => 0,
                'paid_fees' => 0,
                'is_active' => 1,
            );

            $fees = $this->Fee_model->getInitialFees($currentSessionData['session_id'], $this->input->post('class_id'));
            //print_r($fees);die;
            if(empty($fees)){
                $this->session->set_flashdata('alertType','failed' );
                $this->session->set_flashdata('message','plz add fees , Fees not found for this class and session...' );
                redirect('student/add');
            }
           //print_r($params);die;
            $student_id = $this->Student_model->add_student($params);

            if ($rte_applicable == 0) {
              
                $payment_parameter = array(
                    'student_id' => $student_id,
                    'academic_year' => $currentSessionData['session'],
                    'session_id' => $currentSessionData['session_id'],
                    'class_id' => $this->input->post('class_id'),
                    'total_amount' => $fees->amount,
                    'paid_amount' => 0,
                    'late_fee' => 0,
                    'payment_seq' => 0,
                    'sync' =>0,
                    'created_by' => $this->session->user_id,
                    'statusID' => 1,    
                );  

            } else {

                $payment_parameter = array(
                    'student_id' => $student_id,
                    'academic_year' => $currentSessionData['session'],
                    'session_id' => $currentSessionData['session_id'],
                    'class_id' => $this->input->post('class_id'),
                    'total_amount' => $fees->amount,
                    'paid_amount' => 0,
                    'late_fee' => 0,
                    'payment_seq' => 0,
                    'sync' =>0,
                    'created_by' => $this->session->user_id,
                    'statusID' => 1,    
                );

            }
            // print_r($payment_parameter);
            // die;
            $payment_id = $this->Payment_model->add_payment($payment_parameter);
            if($payment_id){
                $this->session->set_flashdata('alertType','success' );
                $this->session->set_flashdata('message','Student Added Successfully..' );
                redirect('student/index');
            }else{
                $this->session->set_flashdata('alertType','failed' );
                $this->session->set_flashdata('message','Unable to add payment....' );
                redirect('student/index');
            }
            
        } else {


            $this->load->model('Clas_model');
            $data['all_class'] = $this->Clas_model->get_all_class();

           

            $data['_view'] = 'student/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a student
     */

    function edit($student_id) {
        // check if the student exists before trying to edit it
        $data['student'] = $this->Student_model->get_student($student_id);
       // print_r($data['student']);die();

        if (isset($data['student']['student_id'])) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('fullname', 'Fullname', 'required');
            $this->form_validation->set_rules('class_id', 'Class Id', 'required');
            $this->form_validation->set_rules('section_id', 'Section Id', 'required');
            $this->form_validation->set_rules('place_of_birth', 'Place Of Birth', 'required');
            $this->form_validation->set_rules('dob', 'Dob', 'required');
            $this->form_validation->set_rules('gender', 'gender', 'required');
            $this->form_validation->set_rules('father_name', 'Father Name', 'required');
            $this->form_validation->set_rules('mobile_no', 'Mobile No', 'required');
            $this->form_validation->set_rules('mother_full_name', 'Mother Full Name', 'required');

            if ($this->form_validation->run()) {
                if (isset($_POST['rte_applicable'])) {
                    $rte_applicable = 1;
                } else {
                    $rte_applicable = 0;
                }
                $config['upload_path'] = './uploads/student/';
                $config['allowed_types'] = 'gif|jpg|png';
                $this->load->library('upload', $config);

                if (!$this->upload->do_upload('image')) {
                    $error = array('error' => $this->upload->display_errors());
                    $image = '';
                } else {
                    $upload_data = $this->upload->data(); //Returns array of containing all of the data related to the file you uploaded.
                    $image = $upload_data['file_name'];
                }
                if ($image == '') {
                    $image = $this->input->post('old_image');
                }
                
                $admission_date = $this->input->post('register_date');
                //class change check
                if(!empty($this->input->post('class_id')) && $this->input->post('class_id') != $data['student']['class_id']){
                    //check if payment done in this session
                    if(empty($data['student']['session_id'])){
                        $this->session->set_flashdata('alertType','failed' );
                        $this->session->set_flashdata('message','Sesion ID is not Set For This Student....' );
                        redirect('student/edit/'.$student_id);
                    }
                    $payment_id = $this->Payment_model->get_payment_id_by_session($data['student']['session_id'],$student_id);
                    
                    $payment_log_data = $this->Payment_log_model->get_payment_log_payment_id($payment_id);

                    if(!empty($payment_log_data)){
                        $this->session->set_flashdata('alertType','failed' );
                        $this->session->set_flashdata('message','Payment is done for this student in this session cannot change class...' );
                        redirect('student/edit/'.$student_id);
                    }
                }

                //class change check
                if($rte_applicable != $data['student']['rte_applicable']){
                    //check if payment done in this session
                    if(empty($data['student']['session_id'])){
                        $this->session->set_flashdata('alertType','failed' );
                        $this->session->set_flashdata('message','Sesion ID is not Set For This Student....' );
                        redirect('student/edit/'.$student_id);
                    }
                    $payment_id = $this->Payment_model->get_payment_id_by_session($data['student']['session_id'],$student_id);
                    
                    $payment_log_data = $this->Payment_log_model->get_payment_log_payment_id($payment_id);

                    if(!empty($payment_log_data)){
                        $this->session->set_flashdata('alertType','failed' );
                        $this->session->set_flashdata('message','Payment is done for this student in this session cannot change RTE Status...' );
                        redirect('student/edit/'.$student_id);
                    }
                }

                $params = array(
                    'class_id' => $this->input->post('class_id'),
                    'section_id' => $this->input->post('section_id'),
                    'rte_applicable' => $rte_applicable,
                    'registration_no' => $this->input->post('registration_no'),
                    'saral_id' => $this->input->post('saral_id'),
                    'fullname' => $this->input->post('fullname'),
                    'aadhar_no' => $this->input->post('aadhar_no'),
                    'gender' => $this->input->post('gender'),
                    'religion' => $this->input->post('religion'),
                    'nationality' => $this->input->post('nationality'),
                    'mother_tounge' => $this->input->post('mother_tounge'),
                    'caste' => $this->input->post('caste'),
                    'category' => $this->input->post('category'),
                    'age' => $this->input->post('age'),
                    'dob' => $this->input->post('dob'),
                    'last_school' => $this->input->post('last_school'),
                    'last_class' => $this->input->post('last_class'),
                    'last_medium' => $this->input->post('last_medium'),
                    'is_last_school_recognize' => $this->input->post('is_last_school_recognize'),
                    'sought_admission_in_class' => $this->input->post('sought_admission_in_class'),
                    'medium' => $this->input->post('medium'),
                    'father_name' => $this->input->post('father_name'),
                    'at_post' => $this->input->post('at_post'),
                    'tahsil' => $this->input->post('tahsil'),
                    'dist' => $this->input->post('dist'),
                    'occupation' => $this->input->post('occupation'),
                    'ph_no' => $this->input->post('ph_no'),
                    'mobile_no' => $this->input->post('mobile_no'),
                    'parent_on_service' => $this->input->post('parent_on_service'),
                    'office_address_phone_no' => $this->input->post('office_address_phone_no'),
                    'mother_full_name' => $this->input->post('mother_full_name'),
                    'annual_income' => $this->input->post('annual_income'),
                    'local_address' => $this->input->post('local_address'),
                    'relation_ship_with_parent' => $this->input->post('relation_ship_with_parent'),
                    //'academic_year' => $this->input->post('academic_year'),
                    'place_of_birth' => $this->input->post('place_of_birth'),
                    'image' => $image,
                    'register_date' => $admission_date,
                    'modified_by'=> $this->session->user_id,
                    'modified_at'=> date("Y-m-d h:i:s"),
                );
                $this->Student_model->update_student($student_id, $params);
                
                

                if( (!empty($this->input->post('class_id')) && $this->input->post('class_id') != $data['student']['class_id'] ) || ($rte_applicable != $data['student']['rte_applicable']) ){
                    if ($rte_applicable == 0) {

                        $fees = $this->Fee_model->getInitialFees($data['student']['session_id'], $this->input->post('class_id'));
                        if(empty($fees)){
                            $this->session->set_flashdata('alertType','failed' );
                            $this->session->set_flashdata('message','plz add fees , Fees not found for this class and session...' );
                            redirect('student/edit/'.$student_id);
                        }
                    
                        $payment_parameter = array(
                            'class_id' => $this->input->post('class_id'),
                            'total_amount' => $fees->amount,
                            'paid_amount' => 0,
                            'modified_by'=> $this->session->user_id,
                            'modified_at'=> date("Y-m-d h:i:s"),

                        );
        
                        // print_r($payment_parameter);
                        // die;
                        
                    } else {
                    
                        $payment_parameter = array(
                            'class_id' => $this->input->post('class_id'),
                            'total_amount' => 0,
                            'paid_amount' => 0,
                            'modified_by'=> $this->session->user_id,
                            'modified_at'=> date("Y-m-d h:i:s"),
                        );
        
                    }

                    $this->Payment_model->update_payment($payment_id,$payment_parameter);

                }
                
                $this->session->set_flashdata('alertType','success' );
                $this->session->set_flashdata('message','Student Edited Successfully....' );
                redirect('student/index');
            } else {
                $this->load->model('Clas_model');
                $data['all_class'] = $this->Clas_model->get_all_class();

                $this->load->model('Section_model');
                $data['all_section'] = $this->Section_model->getSectionByClass($data['student']['class_id']);

       
                $data['_view'] = 'student/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The student you are trying to edit does not exist.');
    }

    /*
     * Deleting student
     */

    function remove($student_id) {
        $student = $this->Student_model->get_student($student_id);
        // check if the student exists before trying to delete it
        if (isset($student['student_id'])) {
            $params = array(
                'is_active'=>0,
                'modified_by'=> $this->session->user_id,
                'modified_at'=> date("Y-m-d h:i:s"),
            );
            $this->Student_model->update_student($student_id,$params);
            redirect('student/index');
        } else
            show_error('The student you are trying to delete does not exist.');
    }

    function getStudentByClassAndSection() {
        $class_id = $this->input->post('class_id');
        $section_id = $this->input->post('section_id');
        $result = $this->Student_model->getStudentByClassAndSection($class_id, $section_id);
        echo json_encode($result);
    }

    function getStudentBySessionClassAndSection() {
        $class_id = $this->input->post('class_id');
        $section_id = $this->input->post('section_id');
        $session_id = $this->input->post('session_id');
        $result = $this->Student_model->getStudentBySessionClassAndSection($session_id,$class_id, $section_id);
        echo json_encode($result);
    }

    function getStudentByClass() {
        $class_id = $this->input->post('class_id');
        $result = $this->Student_model->getStudentByClass($class_id);
        echo json_encode($result);
    }

    function getSectionsByClass() {
        $class_id = $this->input->post('class_id'); // Fetch class ID from AJAX request

        if ($class_id) {
            $this->load->model('Section_model'); // Load your model that interacts with the database
        $section= $this->Section_model->getSectionsByClass($class_id); // Call model to get sections
        echo json_encode($section); // Return sections as JSON
    }
    
        echo json_encode([]);
    
}
    

    function uploadStudentFromExcel() {

        $data['_view'] = 'student/upload-from-excel';
        $this->load->view('layouts/main', $data);
    }

    function import() {
        $this->load->library('excel');
        if ($_FILES['file']['name'] != '') {
            $config['upload_path'] = './uploads/excels/';
            $config['allowed_types'] = 'xls|xlsx';
            $config['max_size'] = 2048;
            $this->load->library('upload', $config);
            $this->upload->initialize($config);

            if (!$this->upload->do_upload('file')) {
                json_error("File Upload Error", $this->upload->display_errors(), 400);
            } else {
                $uploadData = $this->upload->data();

                $object = PHPExcel_IOFactory::load($uploadData['full_path']);
                foreach ($object->getWorksheetIterator() as $worksheet) {
                    $highestRow = $worksheet->getHighestRow();
                    //print_r($highestRow);die();
                    $highestColumn = $worksheet->getHighestColumn();
                    for ($row = 2; $row <= $highestRow; $row++) {
                        $registration_no = $worksheet->getCellByColumnAndRow(0, $row)->getValue();
                        $fullname = $worksheet->getCellByColumnAndRow(1, $row)->getValue();
                        $father_name = $worksheet->getCellByColumnAndRow(2, $row)->getValue();
                        $mother_full_name = $worksheet->getCellByColumnAndRow(3, $row)->getValue();
                        
                        //session 
                        $session = $worksheet->getCellByColumnAndRow(4, $row)->getValue();
                        //print_r($session);die();
                        // if(empty($session)){
                        //     $this->session->set_flashdata('alertType','failed' );
                        //     $this->session->set_flashdata('message','session value is empty on row no -'.$row );
                        //     redirect('student/uploadStudentFromExcel');
                        // }
                        
                        $session_id = $this->getSessionByAcadamicYear($session);
                        // if(empty($session_id)){
                        //     $this->session->set_flashdata('alertType','failed' );
                        //     $this->session->set_flashdata('message','session value is not valid on row no -'.$row );
                        //     redirect('student/uploadStudentFromExcel');
                        // }

                        //class 
                        $class = $worksheet->getCellByColumnAndRow(5, $row)->getValue();
                        // if(empty($class)){
                        //     $this->session->set_flashdata('alertType','failed' );
                        //     $this->session->set_flashdata('message','class value is empty on row no -'.$row );
                        //     redirect('student/uploadStudentFromExcel');
                        // }
                        $class_id = $this->getClassByNum($class);
                        // if(empty($class_id)){
                        //     $this->session->set_flashdata('alertType','failed' );
                        //     $this->session->set_flashdata('message','class value is not valid on row no -'.$row );
                        //     redirect('student/uploadStudentFromExcel');
                        // }
                        //section
                        $section = $worksheet->getCellByColumnAndRow(6, $row)->getValue();
                        // if(empty($section)){
                        //     $this->session->set_flashdata('alertType','failed' );
                        //     $this->session->set_flashdata('message','section value is empty on row no -'.$row );
                        //     redirect('student/uploadStudentFromExcel');
                        // }
                        $section_id = $this->getSectionByNameAndClassId($class_id, $section);
                        // if(empty($section_id)){
                        //     $this->session->set_flashdata('alertType','failed' );
                        //     $this->session->set_flashdata('message','section value is not valid on row no -'.$row );
                        //     redirect('student/uploadStudentFromExcel');
                        // }
                        //--------------------------------------------------------------------//
                        $gender = $worksheet->getCellByColumnAndRow(7, $row)->getValue();
                        $aadhar_no = $worksheet->getCellByColumnAndRow(8, $row)->getValue();
                        $saral_id = $worksheet->getCellByColumnAndRow(9, $row)->getValue();
                        $apar_no = $worksheet->getCellByColumnAndRow(10, $row)->getValue();
                        $udic_no = $worksheet->getCellByColumnAndRow(11, $row)->getValue();
                        $religion = $worksheet->getCellByColumnAndRow(12, $row)->getValue();
                        $caste = $worksheet->getCellByColumnAndRow(13, $row)->getValue();
                        $category = $worksheet->getCellByColumnAndRow(14, $row)->getValue();
                        $nationality = $worksheet->getCellByColumnAndRow(15, $row)->getValue();
                        $mother_tounge = $worksheet->getCellByColumnAndRow(16, $row)->getValue();
                        $dob_raw = $worksheet->getCellByColumnAndRow(17, $row)->getValue();
                        $dob = str_replace('/','-',$dob_raw);
                        $place_of_birth = $worksheet->getCellByColumnAndRow(18, $row)->getValue();
                        $age = $worksheet->getCellByColumnAndRow(19, $row)->getValue();
                        $last_school = $worksheet->getCellByColumnAndRow(20, $row)->getValue();
                        $last_class = $worksheet->getCellByColumnAndRow(21, $row)->getValue();
                        $last_medium = $worksheet->getCellByColumnAndRow(22, $row)->getValue();
                        $is_last_school_recognize = $worksheet->getCellByColumnAndRow(23, $row)->getValue();
                        
                        $at_post = $worksheet->getCellByColumnAndRow(24, $row)->getValue();
                        $tahsil = $worksheet->getCellByColumnAndRow(25, $row)->getValue();
                        $dist = $worksheet->getCellByColumnAndRow(26, $row)->getValue();
                        $occupation = $worksheet->getCellByColumnAndRow(27, $row)->getValue();
                        $ph_no = $worksheet->getCellByColumnAndRow(28, $row)->getValue();
                        $mobile_no = $worksheet->getCellByColumnAndRow(29, $row)->getValue();
                        $parent_on_service = $worksheet->getCellByColumnAndRow(30, $row)->getValue();
                        $office_address_phone_no = $worksheet->getCellByColumnAndRow(31, $row)->getValue();
                        
                        $annual_income = $worksheet->getCellByColumnAndRow(32, $row)->getValue();
                        $local_address = $worksheet->getCellByColumnAndRow(33, $row)->getValue();
                        $relation_ship_with_parent = $worksheet->getCellByColumnAndRow(34, $row)->getValue();
                        $admission_date_raw = $worksheet->getCellByColumnAndRow(35, $row)->getValue();
                        $admission_date = str_replace('/','-',$admission_date_raw);
                        $rte_applicable = $worksheet->getCellByColumnAndRow(36, $row)->getValue();
                        if($rte_applicable == 1 || strtoupper($rte_applicable) == 'YES'){$rte= 1;}else{$rte= 0;}
                        //print_r($admission_date."--");  
                        // print_r($dob);
                        // die();
                        $is_active = 1;

                        $data[] = array(
                            'registration_no' => $registration_no,
                            'fullname' => $fullname,
                            'father_name' => $father_name,
                            'mother_full_name' => $mother_full_name,
                            'session_id' => $session_id,
                            'academic_year' => $session,
                            'class_id' => $class_id,
                            'section_id' => $section_id,
                            'gender' => $gender,
                            'aadhar_no' => $aadhar_no,
                            'saral_id' => $saral_id,
                            // 'apar_no' => $apar_no,
                            // 'udic_no' => $udic_no,
                            'religion' => $religion,
                            'caste' => $caste,
                            'category' => $category,
                            'nationality' => $nationality,
                            'mother_tounge' => $mother_tounge,
                            'dob' => date("Y-m-d", strtotime($dob)),
                            'place_of_birth'=>$place_of_birth,
                            'age' => $age,
                            'last_school' => $last_school,
                            'last_class' => $last_class,
                            'last_medium' => $last_medium,
                            'is_last_school_recognize' => $is_last_school_recognize,
                            'at_post' => $at_post,
                            'tahsil' => $tahsil,
                            'dist' => $dist,
                            'occupation' => $occupation,
                            'ph_no' => $ph_no,
                            'mobile_no' => $mobile_no,
                            'parent_on_service' => $parent_on_service,
                            'office_address_phone_no' => $office_address_phone_no,
                            'annual_income' => $annual_income,
                            'local_address' => $local_address,
                            'relation_ship_with_parent' => $relation_ship_with_parent,
                            'register_date' => $admission_date_raw,
                            'rte_applicable'=>$rte,
                            'is_active' => $is_active,
                            'old_fees' => 0,
                            'paid_fees' => 0,
                            
                        );
                        
                        // print_r($data);
                        // die();
                    }
                }
                $count=0;
               
                // print_r($data);
                // die();
                foreach ($data as $k => $v) {
                    
                   //print_r($v);die();
                    $student_id = $this->Student_model->add_student($v);
                    $totalfees = 0;

                    if($v['rte_applicable']){
                        //RTE Applicable Students
                        $feesby_type = $this->Fee_model->getFeeBySessionClass($v['session_id'],$v['class_id']);
                        if (!empty($feesby_type)) {
                            foreach ($feesby_type as $key => $value) {
                                switch ($value->fees_for) {
                                    case 'Prospectus Fee':
                                        $prospectus_fee = $value->amount;
                                        $totalfees = $totalfees + $value->amount;
                                        break;
                                    case 'Admission Fees':
                                        $admission_fee = 0;
                                        break;
                                    case 'Uniform Fees';
                                        $uniform_fee = $value->amount;
                                        $totalfees = $totalfees + $value->amount;
                                        break;
                                    case 'Books Fees':
                                        $books_fee = $value->amount;
                                        $totalfees = $totalfees + $value->amount;
                                        break;
                                    case 'Tuition Fees':
                                        $tuition_fee = 0;
                                        break;
                                    case 'Term Fees':
                                        $term_fee = 0;
                                        break;
                                    case 'Activity Fees':
                                        $activity_fee = 0;
                                        break;
                                    default:
                                        # code...
                                        break;
                                }
                            }
                        }

                     
                    }else{
                        // Non RTE Students
                        $feesby_type = $this->Fee_model->getFeeBySessionClass($v['session_id'],$v['class_id']);
                        if (!empty($feesby_type)) {
                            foreach ($feesby_type as $key => $value) {
                                switch ($value->fees_for) {
                                    case 'Prospectus Fee':
                                        $prospectus_fee = $value->amount;
                                        $totalfees = $totalfees + $value->amount;
                                        break;
                                    case 'Admission Fees':
                                        $admission_fee = $value->amount;
                                        $totalfees = $totalfees + $value->amount;
                                        break;
                                    case 'Uniform Fees';
                                        $uniform_fee = $value->amount;
                                        $totalfees = $totalfees + $value->amount;
                                        break;
                                    case 'Books Fees':
                                        $books_fee = $value->amount;
                                        $totalfees = $totalfees + $value->amount;
                                        break;
                                    case 'Tuition Fees':
                                        $tuition_fee = $value->amount;
                                        $totalfees = $totalfees + $value->amount;
                                        break;
                                    case 'Term Fees':
                                        $term_fee = $value->amount;
                                        $totalfees = $totalfees + $value->amount;
                                        break;
                                    case 'Activity Fees':
                                        $activity_fee = $value->amount;
                                        $totalfees = $totalfees + $value->amount;
                                        break;
                                    default:
                                        # code...
                                        break;
                                }
                            }
                        }
                        
                    }

                    $payment_parameter = array(
                        'student_id' => $student_id,
                        'session_id' => $v['session_id'],
                        'class_id' => $v['class_id'],
                        'academic_year' => $v['academic_year'],
                        'total_amount' => $totalfees,
                        'paid_amount' => 0,
                        'prospectus_fee' =>$prospectus_fee,
                        'admission_fee' => $admission_fee,
                        'uniform_fee'=> $uniform_fee,
                        'books_fee' =>$books_fee,
                        'tuition_fee' =>$tuition_fee,
                        'term_fee' => $term_fee,
                        'activity_fee' =>$activity_fee,
                        'late_fee' => 0,
                        'statusID' => 1,
                    );
                    //print_r($payment_parameter);die();
                    $payment_id = $this->Payment_model->add_payment($payment_parameter);
                    $count++;
                }
                //$k++;
                $this->session->set_flashdata('msg', count($data) . ' Students Records Are Added');
                redirect('student/index');
            }
        } else {
            $this->session->set_flashdata('msg', 'Please upload valid file');
            $data['_view'] = 'student/upload-from-excel';
            $this->load->view('layouts/main', $data);
        }
    }

    function getStudentNoByClass() {
        $class = $this->input->post('class_id');
        $result = $this->Student_model->getStudentNoByClass($class);
        echo json_encode($result);
    }

    function getStudentById() {
        $student_id = $this->input->post('student_id');
        $result = $this->Student_model->getStudentData($student_id);
        echo json_encode($result);
    }

    function getClassByNum($num) {
        $result = $this->Student_model->getClassByNum($num);
        return $result->class_id;
    }

    function getSessionByAcadamicYear($session) {
       
        $session_id = $this->Academic_year_model->getSessionByAcadamicYear($session);
        return $session_id;
    }

    function getSectionByNameAndClassId($class_id, $section) {
        $result = $this->Student_model->getSectionByNameAndClassId($class_id, $section);
        return $result;
    }

    function history($student_id = 0) {
        $data['student_details'] = $this->Student_model->get_student($student_id);
        $this->load->model("Payment_model");
        $this->load->model("Academic_year_model");
        $data['payment_history'] = $this->Payment_model->getPaymentHistory($student_id);
        $data['transactions'] = $this->Payment_model->getTransactions($student_id);
//        var_dump($data);die;
        $data['_view'] = 'student/history';
        $this->load->view('layouts/main', $data);
    }

    function getStudentDetailsview($student_id = 0) {
        $data['student_details'] = $this->Student_model->get_student($student_id);
        $this->load->model("Payment_model");
        $data['payment_history'] = $this->Payment_model->getPaymentHistory($student_id);
        $data['transactions'] = $this->Payment_model->getTransactions($student_id);
//        var_dump($data);die;
        $data['_view'] = 'student/view';
//        var_dump($data);die;
        $this->load->view('layouts/main', $data);
    }

    function getActiveStudent() {
        $this->load->model('Student_model');
        $data = $this->Student_model->getActiveStudent();
        echo json_encode($data);
    }

}
