<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Clas_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get clas by class_id
     */
    function get_clas($class_id)
    {
        return $this->db->get_where('class',array('class_id'=>$class_id))->row_array();
    }
        
    /*
     * Get all class
     */
    function get_all_class()
    {
        $this->db->order_by('class_id', 'desc');
        return $this->db->get('class')->result_array();
    }
        
    /*
     * function to add new clas
     */
    function add_clas($params)
    {
        $this->db->insert('class',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update clas
     */
    function update_clas($class_id,$params)
    {
        $this->db->where('class_id',$class_id);
        return $this->db->update('class',$params);
    }
    
    /*
     * function to delete clas
     */
    function delete_clas($class_id)
    {
        return $this->db->delete('class',array('class_id'=>$class_id));
    }
}
