<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Expense_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get expense by expenses_id
     */
    function get_expense($expenses_id)
    {
        return $this->db->get_where('expenses',array('expenses_id'=>$expenses_id))->row_array();
    }
        
    /*
     * Get all expenses
     */
    function get_all_expenses()
    {
        $this->db->order_by('expenses_id', 'desc');
        return $this->db->get('expenses')->result_array();
    }
        
    /*
     * function to add new expense
     */
    function add_expense($params)
    {
        $this->db->insert('expenses',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update expense
     */
    function update_expense($expenses_id,$params)
    {
        $this->db->where('expenses_id',$expenses_id);
        return $this->db->update('expenses',$params);
    }
    
    /*
     * function to delete expense
     */
    function delete_expense($expenses_id)
    {
        return $this->db->delete('expenses',array('expenses_id'=>$expenses_id));
    }
}
