<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fee_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get fee by fees_id
     */
    function get_fee($class_id)
    {
        $this->db->where('class_id',$class_id);
        return $this->db->get('fees')->result_array();
//        return $this->db->get_where('fees',array('class_id'=>$class_id))->result_array();
    }
        
    /*
     * Get all fees
     */
    function get_all_fees()
    {
        $this->db->select('GROUP_CONCAT(CONCAT(f.fees_for,"-",f.amount)) fees_for,sum(f.amount) as total_fee,c.numeric_name,c.class_id');
        $this->db->from('fees f');
        $this->db->join("class c",'f.class_id=c.class_id','inner');
        $this->db->order_by('fees_id', 'desc');
        $this->db->group_by('c.class_id');
//        $query = $this->db->get()->result_array();
//        var_dump($this->db->last_query());die;
        return $this->db->get()->result_array();
    }
        
    /*
     * function to add new fee
     */
    function add_fee($params)
    {
        $this->db->insert('fees',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update fee
     */
    function update_fee($fees_id,$params)
    {
        $this->db->where('fees_id',$fees_id);
        return $this->db->update('fees',$params);
    }
    
    /*
     * function to delete fee
     */
    function delete_fee($fees_id)
    {
        return $this->db->delete('fees',array('fees_id'=>$fees_id));
    }
    function deleteClassFees($class_id){
        $this->db->delete('fees',array('class_id'=>$class_id));
    }
    
    function getTotalFeeByClass($class_id){
        $this->db->select('sum(amount) as total_amount');
        $this->db->from('fees');
        $this->db->where('class_id',$class_id);
        
        $query = $this->db->get();
//        var_dump($this->db->last_query());die;
        return $query->row();
    }

    function getTotalFeeByFeesType($class_id){
        $this->db->select('fees_for, amount');
        $this->db->from('fees');
        $this->db->where('class_id',$class_id);
        
        $query = $this->db->get();
//        var_dump($this->db->last_query());die;
        return $query->result_array();
    }
}
