<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Management_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get management by id
     */
    function get_management($id)
    {
        return $this->db->get_where('management',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all management
     */
    function get_all_management()
    {
        $this->db->order_by('id', 'asc');
        return $this->db->get('management')->result_array();
    }
        
    /*
     * function to add new management
     */
    function add_management($params)
    {
        $this->db->insert('management',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update management
     */
    function update_management($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('management',$params);
    }
    
    /*
     * function to delete management
     */
    function delete_management($id)
    {
        return $this->db->delete('management',array('id'=>$id));
    }
}
