<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Dashboard_model');
                
        
    }

    function index()
    {
        $data['_view'] = 'dashboard';
        $data['no_of_student'] = $this->Dashboard_model->getCountActiveStudent();
        $data['no_of_teacher'] = $this->Dashboard_model->getCountActiveTeacher();
        $data['sms_count'] = $this->Dashboard_model->getSmsCount();
        $data['fees_collected_today'] = $this->Dashboard_model->getPaymentCount();
        $year = date('y');
        $next_year = $year+1;
        $academic_year = '20'.$year.'-'.$next_year;
        $data['admitted_current_year']= $this->Dashboard_model->getCurrentYearCount($academic_year);
        $data['fees_collected'] = $this->Dashboard_model->getCurrentYearFees($academic_year);
        $data['class_student'] = $this->Dashboard_model->classStudent();
        $data['fees_by_month'] = $this->Dashboard_model->getMonthFeeCollected($academic_year);
        $data['fee_collected_and_remaining'] = $this->Dashboard_model->getFeesData();
//        var_dump($data);die;
        $this->load->view('layouts/main',$data);
    }
}
