<?php

/*
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Leaving_certificate extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Leaving_certificate_model');
        $this->load->model('Student_model');
    }

    /*
     * Listing of leaving_certificate
     */

    function index() {
        $data['leaving_certificate'] = $this->Leaving_certificate_model->get_all_leaving_certificate();

        $data['_view'] = 'leaving/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new leaving_certificate
     */

    function add() {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('fullname', 'Full Name', 'required');
        $this->form_validation->set_rules('father_name', 'Father Name', 'required');
        $this->form_validation->set_rules('mother_name', 'Mother Name', 'required');
        $this->form_validation->set_rules('surname', 'Surname', 'required');
        $this->form_validation->set_rules('b_tah', 'Birth Place Tahsil');
        $this->form_validation->set_rules('b_dist', 'Birth Place District');
        $this->form_validation->set_rules('b_state', 'Birth Place State');
        $this->form_validation->set_rules('b_country', 'Birth Place Country');
        $this->form_validation->set_rules('saral_id', 'Saral Id', 'required');
        $this->form_validation->set_rules('progress', 'Progress', 'required');
        $this->form_validation->set_rules('reason', 'Reason', 'required');
        $this->form_validation->set_rules('remark', 'Remark', 'required');
        $this->form_validation->set_rules('student_id', 'Student Id', 'required');
        $this->form_validation->set_rules('place_of_birth', 'Place Of Birth','required');
        $this->form_validation->set_rules('studying_from_class', 'Studying From Class ','required');


        if ($this->form_validation->run()) {
            $date_of_leave = strtr($this->input->post('date_of_leave'), '/', '-');
            $date_of_issue = strtr($this->input->post('date_of_issue'), '/', '-');
            $params = array(
                'student_id' => $this->input->post('student_id'),
                'fullname' => $this->input->post('fullname'),
                'father_name' => $this->input->post('father_name'),
                'mother_name' => $this->input->post('mother_name'),
                'surname' => $this->input->post('surname'),
                'b_tah' => $this->input->post('b_tah'),
                'b_dist' => $this->input->post('b_dist'),
                'b_state' => $this->input->post('b_state'),
                'b_country' => $this->input->post('b_country'),
                'progress' => $this->input->post('progress'),
                'reason' => $this->input->post('reason'),
                'remark' => $this->input->post('remark'),
                'academic_year' => $this->input->post('academic_year'),
                'date_of_leave' => date('Y-m-d', strtotime($date_of_leave)),
                'date_of_issueing' => date('Y-m-d', strtotime($date_of_issue)),
                'studying_since' => $this->input->post('studying_since'),
                'studying_from_class'=>$this->input->post('studying_from_class'),
                'created_date' => date('Y-m-d'),
            );
            $leaving_certificate_id = $this->Leaving_certificate_model->add_leaving_certificate($params);
            $student_param = array(
                'is_active' => 0,
            );
            $this->Student_model->update_student($this->input->post('student_id'), $student_param);
            redirect('leaving_certificate/index');
        } else {

            $this->load->model('Clas_model');
            $data['all_class'] = $this->Clas_model->get_all_class();

            $data['_view'] = 'leaving/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a leaving_certificate
     */

    function edit($leaving_id) {
        // check if the leaving_certificate exists before trying to edit it
        $data['leaving_certificate'] = $this->Leaving_certificate_model->get_leaving_certificate($leaving_id);
        if (isset($data['leaving_certificate']['leaving_id'])) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('fullname', ' Fullname', 'required');
            $this->form_validation->set_rules('father_name', 'Father Name', 'required');
            $this->form_validation->set_rules('mother_name', 'Mother Name', 'required');
            $this->form_validation->set_rules('surname', 'Surname');
//            $this->form_validation->set_rules('b_tah', 'B Tah');
//            $this->form_validation->set_rules('b_dist', 'B Dist');
            $this->form_validation->set_rules('b_state', 'B State', 'required');
            $this->form_validation->set_rules('b_country', 'B Country', 'required');
            $this->form_validation->set_rules('progress', 'Progress', 'required');
            $this->form_validation->set_rules('reason', 'Reason', 'required');
            $this->form_validation->set_rules('remark', 'Remark', 'required');
            $this->form_validation->set_rules('student_id', 'Student Id', 'required');
              $this->form_validation->set_rules('place_of_birth', 'Place Of Birth','required');
        $this->form_validation->set_rules('studying_from_class', 'Studying From Class ','required');
        $this->form_validation->set_rules('registration_no', 'GR NO ','required');

            if ($this->form_validation->run()) {
                $date_of_leave = strtr($this->input->post('date_of_leave'), '/', '-');
                $date_of_issue = strtr($this->input->post('date_of_issue'), '/', '-');
                $params = array(
                    'student_id' => $this->input->post('student_id'),
                    'fullname' => $this->input->post('fullname'),
                    'father_name' => $this->input->post('father_name'),
                    'mother_name' => $this->input->post('mother_name'),
                    'surname' => $this->input->post('surname'),
                    'b_tah' => $this->input->post('b_tah'),
                    'b_dist' => $this->input->post('b_dist'),
                    'b_state' => $this->input->post('b_state'),
                    'b_country' => $this->input->post('b_country'),
                    'progress' => $this->input->post('progress'),
                    'reason' => $this->input->post('reason'),
                    'remark' => $this->input->post('remark'),
                    'academic_year' => $this->input->post('academic_year'),
                    'date_of_leave' => date('Y-m-d', strtotime($date_of_leave)),
                    'date_of_issueing' => date('Y-m-d', strtotime($date_of_issue)),
                    'studying_since' => $this->input->post('studying_since'),
                    'studying_from_class'=>$this->input->post('studying_from_class'),
                );

                $this->Leaving_certificate_model->update_leaving_certificate($leaving_id, $params);
                redirect('leaving_certificate/index');
            } else {
                $this->load->model('Student_model');
                $data['all_student'] = $this->Student_model->get_all_student();

                $data['_view'] = 'leaving/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The leaving_certificate you are trying to edit does not exist.');
    }

    /*
     * Deleting leaving_certificate
     */

    function remove($leaving_id) {

        $leaving_certificate = $this->Leaving_certificate_model->get_leaving_certificate($leaving_id);

        // check if the leaving_certificate exists before trying to delete it
        if (isset($leaving_certificate['leaving_id'])) {
            $this->Leaving_certificate_model->delete_leaving_certificate($leaving_id);
            redirect('leaving_certificate/index');
        } else
            show_error('The leaving_certificate you are trying to delete does not exist.');
    }

    function view($leaving_id) {
        $data['leaving_certificate'] = $this->Leaving_certificate_model->get_leaving_certificate($leaving_id);
        $data['student'] = $this->Student_model->getStudentData($data['leaving_certificate']['student_id']);

        // echo "<pre>";
        // var_dump($data);die;
        $data['_view'] = 'leaving/view';
        $this->load->view('layouts/main', $data);
    }

}
