<?php

/*
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Teacher extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Teacher_model');
    }

    /*
     * Listing of teacher
     */

    function index() {
        $data['teacher'] = $this->Teacher_model->get_all_teachers();

        $data['_view'] = 'teacher/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new teacher
     */

    function add() {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('fname', 'Fname', 'required');
        $this->form_validation->set_rules('lname', 'Lname', 'required');
        $this->form_validation->set_rules('date_of_birth', 'Date Of Birth', 'required');
        $this->form_validation->set_rules('contact', 'Contact', 'required');
        $this->form_validation->set_rules('email', 'Email', 'required|valid_email');
        $this->form_validation->set_rules('address', 'Address', 'required');

        if ($this->form_validation->run()) {
            $config['upload_path'] = './uploads/teachers/';
            $config['allowed_types'] = 'gif|jpg|png';
            $this->load->library('upload', $config);

            if (!$this->upload->do_upload('image')) {
                $error = array('error' => $this->upload->display_errors());
                $image = '';
            } else {
                $upload_data = $this->upload->data(); //Returns array of containing all of the data related to the file you uploaded.
                $image = $upload_data['file_name'];
            }
            $params = array(
                'register_date' => date('Y-m-d'),
                'fname' => $this->input->post('fname'),
                'lname' => $this->input->post('lname'),
                'date_of_birth' => date('Y-m-d',strtotime(strtr($this->input->post('date_of_birth'),'/','-'))),
                'age' => $this->input->post('age'),
                'contact' => $this->input->post('contact'),
                'email' => $this->input->post('email'),
                'address' => $this->input->post('address'),
                'city' => $this->input->post('city'),
                'image' => $image,
                'designation' => $this->input->post('designation'),
                'category' => $this->input->post('category')
            );
            
           

            $teacher_id = $this->Teacher_model->add_teacher($params);
            redirect('teacher/index');
        } else {
            $data['_view'] = 'teacher/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a teacher
     */

    function edit($teacher_id) {
        // check if the teacher exists before trying to edit it
        $data['teacher'] = $this->Teacher_model->get_teacher($teacher_id);

        if (isset($data['teacher']['teacher_id'])) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('fname', 'Fname', 'required');
            $this->form_validation->set_rules('lname', 'Lname', 'required');
            $this->form_validation->set_rules('date_of_birth', 'Date Of Birth', 'required');
            $this->form_validation->set_rules('contact', 'Contact', 'required');
            $this->form_validation->set_rules('email', 'Email', 'required|valid_email');
            $this->form_validation->set_rules('address', 'Address', 'required');

            if ($this->form_validation->run()) {
                $config['upload_path'] = './uploads/teachers/';
                $config['allowed_types'] = 'gif|jpg|png';
                $this->load->library('upload', $config);

                if (!$this->upload->do_upload('image')) {
                    $error = array('error' => $this->upload->display_errors());
                    $image = '';
                } else {
                    $upload_data = $this->upload->data(); //Returns array of containing all of the data related to the file you uploaded.
                    $image = $upload_data['file_name'];
                }

                if ($image == '') {
                    $image = $this->input->post('old_image');
                }
                $params = array(
                    'fname' => $this->input->post('fname'),
                    'lname' => $this->input->post('lname'),
                    'date_of_birth' => date('Y-m-d',strtotime(strtr($this->input->post('date_of_birth'),'/','-'))),
                    'age' => $this->input->post('age'),
                    'contact' => $this->input->post('contact'),
                    'email' => $this->input->post('email'),
                    'address' => $this->input->post('address'),
                    'city' => $this->input->post('city'),
                    'image' => $image,
                    'designation' => $this->input->post('designation'),
                    'category' => $this->input->post('category')
                );

                $this->Teacher_model->update_teacher($teacher_id, $params);
                redirect('teacher/index');
            } else {
                $data['_view'] = 'teacher/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The teacher you are trying to edit does not exist.');
    }

    /*
     * Deleting teacher
     */

    function remove($teacher_id) {
        $teacher = $this->Teacher_model->get_teacher($teacher_id);

        // check if the teacher exists before trying to delete it
        if (isset($teacher['teacher_id'])) {
            $this->Teacher_model->delete_teacher($teacher_id);
            redirect('teacher/index');
        } else
            show_error('The teacher you are trying to delete does not exist.');
    }

}
