<?php

/*
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Topper extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Topper_model');
    }

    /*
     * Listing of toppers
     */

    function index() {
        $data['toppers'] = $this->Topper_model->get_all_toppers();

        $data['_view'] = 'topper/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new topper
     */

    function add() {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('name', 'Name', 'required');
        $this->form_validation->set_rules('year', 'Year', 'required');
        $this->form_validation->set_rules('class', 'Class', 'required');

        if ($this->form_validation->run()) {
            $config['upload_path'] = './uploads/topper/';
            $config['allowed_types'] = 'gif|jpg|png';
            $this->load->library('upload', $config);

            if (!$this->upload->do_upload('image')) {
                $error = array('error' => $this->upload->display_errors());
                $image = '';
            } else {
                $upload_data = $this->upload->data(); //Returns array of containing all of the data related to the file you uploaded.
                $image = $upload_data['file_name'];
            }
            $params = array(
                'image' => $image,
                'name' => $this->input->post('name'),
                'year' => $this->input->post('year'),
                'class' => $this->input->post('class'),
            );

            $topper_id = $this->Topper_model->add_topper($params);
            redirect('topper/index');
        } else {
            $data['_view'] = 'topper/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a topper
     */

    function edit($id) {
        // check if the topper exists before trying to edit it
        $data['topper'] = $this->Topper_model->get_topper($id);

        if (isset($data['topper']['id'])) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('name', 'Name', 'required');
            $this->form_validation->set_rules('year', 'Year', 'required');
            $this->form_validation->set_rules('class', 'Class', 'required');

            if ($this->form_validation->run()) {
                $config['upload_path'] = './uploads/topper/';
                $config['allowed_types'] = 'gif|jpg|png';
                $this->load->library('upload', $config);

                if (!$this->upload->do_upload('image')) {
                    $error = array('error' => $this->upload->display_errors());
                    $image = '';
                } else {
                    $upload_data = $this->upload->data(); //Returns array of containing all of the data related to the file you uploaded.
                    $image = $upload_data['file_name'];
                }

                if ($image == '') {
                    $image = $this->input->post('old_image');
                }
                $params = array(
                    'image' => $image,
                    'name' => $this->input->post('name'),
                    'year' => $this->input->post('year'),
                    'class' => $this->input->post('class'),
                );

                $this->Topper_model->update_topper($id, $params);
                redirect('topper/index');
            } else {
                $data['_view'] = 'topper/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The topper you are trying to edit does not exist.');
    }

    /*
     * Deleting topper
     */

    function remove($id) {
        $topper = $this->Topper_model->get_topper($id);

        // check if the topper exists before trying to delete it
        if (isset($topper['id'])) {
            $this->Topper_model->delete_topper($id);
            redirect('topper/index');
        } else
            show_error('The topper you are trying to delete does not exist.');
    }

}
