<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Attendance_leave_model extends CI_Model 
{ 
     function __construct()
      {
          parent::__construct();
      }
      /*
        * Get attendance_leave by leaveID 
      */ 
      function get_attendance_leave($leaveID)
      {
        try{
           return $this->db->get_where('attendance_leave',array('leaveID'=>$leaveID))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Attendance_leave_model Model : Error in get_attendance_leave function - ' . $ex);
           }  
      }
      /*
        * Get attendance_leave by  column name
      */ 
      function get_attendance_leavebyclm_name($clm_name,$clm_value)
      {
        try{
           return $this->db->get_where('attendance_leave',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Attendance_leave_model Madel : Error in get_attendance_leavebyclm_name function - ' . $ex);
           }  
      }
     /*
        * Get All attendance_leave count 
      */ 
      function get_all_attendance_leave_count()
      {
        try{
           $this->db->from('attendance_leave');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('Attendance_leave_model model : Error in get_all_attendance_leave_count function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join attendance_leavecount 
      */ 
      function get_all_with_asso_attendance_leave()
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Attendance_leave_model model : Error in get_all_with_asso_attendance_leave function - ' . $ex);
           }  
      }
      /*
          * Get all attendance_leave 
      */ 
      function get_all_attendance_leave($params = array())
      {
        try{
              $this->db->order_by('leaveID', 'desc');
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('attendance_leave')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Attendance_leave_model model : Error in get_all_attendance_leave function - ' . $ex);
           }  
      } 
      /*
         * function to add new attendance_leave 
      */
      function add_attendance_leave($params)
      {
        try{
          $this->db->insert('attendance_leave',$params);
        return $this->db->insert_id();
           } catch (Exception $ex) {
             throw new Exception('Attendance_leave_model model : Error in add_attendance_leave function - ' . $ex);
           }  
      }
      /* 
          * function to update attendance_leave 
      */
      function update_attendance_leave($leaveID,$params)
      {
        try{
            $this->db->where('leaveID',$leaveID);
        return $this->db->update('attendance_leave',$params);
           } catch (Exception $ex) {
             throw new Exception('Attendance_leave_model model : Error in update_attendance_leave function - ' . $ex);
           }  
       }
     /* 
          * function to delete attendance_leave 
      */
       function delete_attendance_leave($leaveID)
       {
        try{
             return $this->db->delete('attendance_leave',array('leaveID'=>$leaveID));
           } catch (Exception $ex) {
             throw new Exception('Attendance_leave_model model : Error in delete_attendance_leave function - ' . $ex);
           }  
       }
      /*
        * Get attendance_leave by  column name where not in particular id
      */ 
      function get_attendance_leavebyclm_name_not_id($clm_name,$clm_value,$where_cond)
      {
        try{
            $this->db->where('leaveID!=', $where_cond);
           return $this->db->get_where('attendance_leave',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Attendance_leave_model model : Error in get_attendance_leavebyclm_name_not_id function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join attendance_leavecount 
      */ 
      function get_all_with_asso_attendance_leave_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Attendance_leave_model model : Error in get_all_with_asso_attendance_leave_by_cat function - ' . $ex);
           }  
      }
      /*
          * Get all attendance_leave_by_cat 
      */ 
      function get_all_attendance_leave_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
              $this->db->order_by('leaveID', 'desc');
              $this->db->where($column_name, $value_id);
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('attendance_leave')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Attendance_leave_model model : Error in get_all_attendance_leave_by_cat function - ' . $ex);
           }  
      } 
 }
