<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Attendance_holidays_model extends CI_Model 
{ 
     function __construct()
      {
          parent::__construct();
      }
      /*
        * Get attendance_holidays by holidayID 
      */ 
      function get_attendance_holidays($holidayID)
      {
        try{
           return $this->db->get_where('attendance_holidays',array('holidayID'=>$holidayID,'statusID' => 1))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Attendance_holidays_model Model : Error in get_attendance_holidays function - ' . $ex);
           }  
      }
      /*
        * Get attendance_holidays by  column name
      */ 
      function get_attendance_holidaysbyclm_name($clm_name,$clm_value)
      {
        try{
           return $this->db->get_where('attendance_holidays',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Attendance_holidays_model Madel : Error in get_attendance_holidaysbyclm_name function - ' . $ex);
           }  
      }
     /*
        * Get All attendance_holidays count 
      */ 
      function get_all_attendance_holidays_count()
      {
        try{
           $this->db->from('attendance_holidays');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('Attendance_holidays_model model : Error in get_all_attendance_holidays_count function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join attendance_holidayscount 
      */ 
      function get_all_with_asso_attendance_holidays()
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Attendance_holidays_model model : Error in get_all_with_asso_attendance_holidays function - ' . $ex);
           }  
      }
      /*
          * Get all attendance_holidays 
      */ 
      function get_all_attendance_holidays($session_id,$params = array())
      {
        try{
              $this->db->order_by('holidayID', 'desc');
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
              $this->db->where('session_id',$session_id);
              $this->db->where('statusID',1);
              return $this->db->get('attendance_holidays')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Attendance_holidays_model model : Error in get_all_attendance_holidays function - ' . $ex);
           }  
      } 
      /*
         * function to add new attendance_holidays 
      */
      function add_attendance_holidays($params)
      {
        try{
          $this->db->insert('attendance_holidays',$params);
        return $this->db->insert_id();
           } catch (Exception $ex) {
             throw new Exception('Attendance_holidays_model model : Error in add_attendance_holidays function - ' . $ex);
           }  
      }
      /* 
          * function to update attendance_holidays 
      */
      function update_attendance_holidays($holidayID,$params)
      {
        try{
            $this->db->where('holidayID',$holidayID);
        return $this->db->update('attendance_holidays',$params);
           } catch (Exception $ex) {
             throw new Exception('Attendance_holidays_model model : Error in update_attendance_holidays function - ' . $ex);
           }  
       }
     /* 
          * function to delete attendance_holidays 
      */
       function delete_attendance_holidays($holidayID)
       {
        try{
             return $this->db->delete('attendance_holidays',array('holidayID'=>$holidayID));
           } catch (Exception $ex) {
             throw new Exception('Attendance_holidays_model model : Error in delete_attendance_holidays function - ' . $ex);
           }  
       }
      /*
        * Get attendance_holidays by  column name where not in particular id
      */ 
      function get_attendance_holidaysbyclm_name_not_id($clm_name,$clm_value,$where_cond)
      {
        try{
            $this->db->where('holidayID!=', $where_cond);
           return $this->db->get_where('attendance_holidays',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Attendance_holidays_model model : Error in get_attendance_holidaysbyclm_name_not_id function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join attendance_holidayscount 
      */ 
      function get_all_with_asso_attendance_holidays_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Attendance_holidays_model model : Error in get_all_with_asso_attendance_holidays_by_cat function - ' . $ex);
           }  
      }
      /*
          * Get all attendance_holidays_by_cat 
      */ 
      function get_all_attendance_holidays_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
              $this->db->order_by('holidayID', 'desc');
              $this->db->where($column_name, $value_id);
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('attendance_holidays')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Attendance_holidays_model model : Error in get_all_attendance_holidays_by_cat function - ' . $ex);
           }  
      }
      
      function get_all_attendance_holidays_by_month($session_id,$date)
      {
        try{
              $this->db->order_by('holidayID', 'desc');
              $this->db->where('session_id',$session_id);
              $this->db->where("DATE_FORMAT(holidayDate,'%Y-%m')", date("Y-m", strtotime($date)));
              $this->db->where('statusID',1);
              return $this->db->get('attendance_holidays')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Attendance_holidays_model model : Error in get_all_attendance_holidays function - ' . $ex);
           }  
      } 
 }
