<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Attendance_Student_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get student_promote by promotion_id
     */
    function get_student_promote($promotion_id)
    {
        return $this->db->get_where('student_promote',array('promotion_id'=>$promotion_id))->row_array();
    }

    function get_student_promote_history($student_id)
    {
        $this->db->select('s.fullname,c.numeric_name as new_class,sec.section_name,d.numeric_name as old_class,p.promotion_id,p.promotion_date');
        $this->db->from('student_promote p');
        $this->db->join('student s','p.student_id=s.student_id','inner');
        $this->db->join('class c','p.new_class_id=c.class_id','inner');
        $this->db->join('class d','p.previous_class_id=d.class_id','inner');
        $this->db->join('section sec','p.section_id=sec.section_id','inner');
        $this->db->where('p.student_id', $student_id);
        return $this->db->get()->result_array();
    }
        
    /*
     * Get all student_promote
     */
    function get_all_student_attendance()
    {
        $this->db->select('s.fullname,c.numeric_name as new_class,sec.section_name,d.numeric_name as old_class,p.promotion_id,p.promotion_date,p.old_academic_year,p.new_academic_year');
        $this->db->select('s.fullname,c.numeric_name as new_class,sec.section_name,d.numeric_name as old_class,p.promotion_id,p.promotion_date,p.old_academic_year,p.new_academic_year');
        
        $this->db->from('student_promote p');
        $this->db->join('student s','p.student_id=s.student_id','inner');
        $this->db->join('class c','p.new_class_id=c.class_id','inner');
        $this->db->join('class d','p.previous_class_id=d.class_id','inner');
        $this->db->join('section sec','p.section_id=sec.section_id','inner');
        //$this->db->order_by('p.promotion_id', 'desc');
        //$this->db->group_by('p.student_id');
        return $this->db->get('student_promote')->result_array();
    }
        
    /*
     * function to add new student_promote
     */
    function add_student_promote($params)
    {
        $this->db->insert('student_promote',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update student_promote
     */
    function update_student_promote($promotion_id,$params)
    {
        $this->db->where('promotion_id',$promotion_id);
        return $this->db->update('student_promote',$params);
    }
    
    /*
     * function to delete student_promote
     */
    function delete_student_promote($promotion_id)
    {
        return $this->db->delete('student_promote',array('promotion_id'=>$promotion_id));
    }

    //Attendance List
    function get_student_attendance_with_session_class_section($session_id,$class_id,$section_id,$date)
      {
        try{
           $this->db->select('*');
           $this->db->from('student_attendance studAtt' );
           $this->db->join('student s','studAtt.student_id=s.student_id','inner');
           $this->db->where('studAtt.session_id',$session_id);
           $this->db->where('studAtt.class_id',$class_id);
           $this->db->where('studAtt.section_id',$section_id);
           $this->db->where('studAtt.date',$date);
           $this->db->where('studAtt.statusID',1);
          $query = $this->db->get();
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Exam_acadamicExams_model model : Error in get_all_with_asso_exam_acadamicExams function - ' . $ex);
           }  
      }

      //List of students
      function get_all_student($session_id,$class_id,$section_id)
    {

        $this->db->select('*');
        $this->db->from('student');
        $this->db->where('session_id',$session_id);
        $this->db->where('class_id',$class_id);
        $this->db->where('section_id',$section_id);
        $this->db->where('is_active',1);

        //$this->db->where('academic_year',$session_id);
        //$this->db->where('class_id',25);
        //$this->db->where('section_id',18);
        //$this->db->where('statusID',1);

        //$this->db->order_by('p.promotion_id', 'desc');
        //$this->db->group_by('p.student_id');
        //return $this->db->last_query();
        return $this->db->get()->result_array();
    }

    function add_student_attendance($params)
    {
        $this->db->insert('student_attendance',$params);
        return $this->db->insert_id();
    }

    function get_student_attendance($attendance_id)
    {
        $this->db->select('*');
        $this->db->from('student_attendance');
        $this->db->where('attendance_id',$attendance_id);
        $this->db->where('statusID',1);
        return $this->db->get()->result_array();
    }

    function update_attendance($attendance_id,$params)
    {
        $this->db->where('attendance_id',$attendance_id);
        return $this->db->update('student_attendance',$params);
    }

    function add_holiday($params)
    {
        $this->db->insert('holiday',$params);
        return $this->db->insert_id();
    }
}
