<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Exam_acadamicExams_model extends CI_Model 
{ 
      function __construct()
      {
          parent::__construct();
      }

      function get_exam_by_exam_id($examID)
      {
        try{
              $this->db->select('*');
              $this->db->from('exam_acadamicExams a' );
              $this->db->join('exam_heads b', 'b.exHeadID=a.exHeadID','left');
              $this->db->where('a.examID',$examID);
              $this->db->where('a.statusID',1);
              return $this->db->get()->result_array();
           } catch (Exception $ex) {
             throw new Exception('Exam_acadamicExams_model model : Error in get_all_exam_acadamicExams function - ' . $ex);
           }  
      } 

      /*
          * Get all exam_acadamicExams 
      */ 
      function get_all_exam_acadamicExamsByGroup($session_id)
      {
        try{  
              $this->db->select('*');
              $this->db->from('exam_acadamicExams a' );
              $this->db->join('exam_heads b', 'b.exHeadID=a.exHeadID','left');
              $this->db->where('a.session_id',$session_id);
              $this->db->where('a.statusID',1);
              $this->db->group_by("a.exHeadID");
              return $this->db->get()->result_array();
           } catch (Exception $ex) {
             throw new Exception('Exam_acadamicExams_model model : Error in get_all_exam_acadamicExams function - ' . $ex);
           }  
      } 

      function get_all_exam_by_class_session($session_id , $class_id)
      {
        try{  
              $this->db->select('*');
              $this->db->from('exam_acadamicExams a' );
              $this->db->join('exam_heads b', 'b.exHeadID=a.exHeadID','left');
              $this->db->where('a.session_id',$session_id);
              $this->db->where('a.class_id',$class_id);
              $this->db->where('b.statusID',1);
              $this->db->where('a.statusID',1);
              return $this->db->get()->result_array();
           } catch (Exception $ex) {
             throw new Exception('Exam_acadamicExams_model model : Error in get_all_exam_acadamicExams function - ' . $ex);
           }  
      } 

      function get_all_extra_parameter($session_id , $class_id, $student_id)
      {
        try{  
              $this->db->select('*');
              $this->db->from('exam_parameters' );
              $this->db->where('session_id',$session_id);
              $this->db->where('class_id',$class_id);
              $this->db->where('student_id',$student_id);
              $this->db->where('statusID',1);
            
              return $this->db->get()->result_array();

           } catch (Exception $ex) {
             throw new Exception('Exam_acadamicExams_model model : Error in get_all_exam_acadamicExams function - ' . $ex);
           }  
      } 


      function get_all_classByexHeadID($exHeadID,$session_id)
      {
        try{
              $this->db->select('*');
              $this->db->from('exam_acadamicExams a' );
              $this->db->join('class c', 'c.class_id=a.class_id','left');
              $this->db->where('a.exHeadID',$exHeadID);
              $this->db->where('a.session_id',$session_id);
              $this->db->where('a.statusID',1);
              $this->db->group_by("a.class_id");
              return $this->db->get()->result_array();
           } catch (Exception $ex) {
             throw new Exception('Exam_acadamicExams_model model : Error in get_all_exam_acadamicExams function - ' . $ex);
           }  
      } 

      function check_recod($exHeadID,$class_id,$session_id)
      {
        try{
           return $this->db->get_where('exam_acadamicExams',array('exHeadID'=>$exHeadID, 'class_id'=>$class_id, 'session_id' => $session_id,'statusID' => 1))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Subject Paper : Error in check record function - ' . $ex);
           }  
      }
      /*
        * Get exam_acadamicExams by  
      */ 
      function get_exam_acadamicExams($examID)
      {
        try{
           return $this->db->get_where('exam_acadamicExams',array('examID'=>$examID))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Exam_acadamicExams_model Model : Error in get_exam_acadamicExams function - ' . $ex);
           }  
      }
      /*
        * Get exam_acadamicExams by  column name
      */ 
      function get_exam_acadamicExamsbyclm_name($clm_name,$clm_value)
      {
        try{
           return $this->db->get_where('exam_acadamicExams',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Exam_acadamicExams_model Madel : Error in get_exam_acadamicExamsbyclm_name function - ' . $ex);
           }  
      }
     /*
        * Get All exam_acadamicExams count 
      */ 
      function get_all_exam_acadamicExams_count()
      {
        try{
           $this->db->from('exam_acadamicExams');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('Exam_acadamicExams_model model : Error in get_all_exam_acadamicExams_count function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join exam_acadamicExamscount 
      */ 
      function get_all_with_asso_exam_acadamicExams()
      {
        try{
           $this->db->select('*');
           $this->db->from('exam_acadamicExams a' );
           $this->db->join('exam_heads b', 'b.exHeadID=a.exHeadID','left');
           $this->db->join('class c', 'c.class_id=a.class_id','left');
           $this->db->join('academic_session d', 'd.session_id=a.session_id','left');
           $this->db->where('a.statusID',1);
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Exam_acadamicExams_model model : Error in get_all_with_asso_exam_acadamicExams function - ' . $ex);
           }  
      }

      /*
        * Get All with associated tables join exam_acadamicExamscount 
      */ 
      function get_all_exam_acadamicExams_with_session_exam($session_id,$exHeadID)
      {
        try{
           $this->db->select('*');
           $this->db->from('exam_acadamicExams a' );
           $this->db->join('exam_heads b', 'b.exHeadID=a.exHeadID','left');
           $this->db->join('class c', 'c.class_id=a.class_id','left');
           $this->db->join('academic_session d', 'd.session_id=a.session_id','left');
           $this->db->where('a.session_id',$session_id);
           $this->db->where('a.exHeadID',$exHeadID);
           $this->db->where('a.statusID',1);
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Exam_acadamicExams_model model : Error in get_all_with_asso_exam_acadamicExams function - ' . $ex);
           }  
      }

      function get_exams_by_class_session($class_id,$session_id)
      {
        try{
           $this->db->select('*');
           $this->db->from('exam_acadamicExams a' );
           $this->db->join('exam_heads b', 'b.exHeadID=a.exHeadID','left');
           $this->db->join('class c', 'c.class_id=a.class_id','left');
           $this->db->join('academic_session d', 'd.session_id=a.session_id','left');
           $this->db->where('a.statusID',1);
           $this->db->where('b.statusID',1);
           $this->db->where('a.class_id',$class_id);
           $this->db->where('a.session_id',$session_id);
           return $this->db->get()->result_array();
        
           } catch (Exception $ex) {
             throw new Exception('Exam_acadamicExams_model model : Error in get_all_with_asso_exam_acadamicExams function - ' . $ex);
           }  
      }
      /*
          * Get all exam_acadamicExams 
      */ 
      function get_all_exam_acadamicExams($params = array())
      {
        try{
              $this->db->order_by('', 'desc');
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('exam_acadamicExams')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Exam_acadamicExams_model model : Error in get_all_exam_acadamicExams function - ' . $ex);
           }  
      } 
      /*
         * function to add new exam_acadamicExams 
      */
      function add_exam_acadamicExams($params)
      {
        try{
          $this->db->insert('exam_acadamicExams',$params);
        return $this->db->insert_id();
           } catch (Exception $ex) {
             throw new Exception('Exam_acadamicExams_model model : Error in add_exam_acadamicExams function - ' . $ex);
           }  
      }
      /* 
          * function to update exam_acadamicExams 
      */
      function update_exam_acadamicExams($examID,$params)
      {
        try{
            $this->db->where('examID',$examID);
        return $this->db->update('exam_acadamicExams',$params);
           } catch (Exception $ex) {
             throw new Exception('Exam_acadamicExams_model model : Error in update_exam_acadamicExams function - ' . $ex);
           }  
       }
     /* 
          * function to delete exam_acadamicExams 
      */
       function delete_exam_acadamicExams($examID)
       {
        try{
             $this->db->where('examID',$examID);
             return $this->db->update('exam_acadamicExams',['statusID'=> 0,'modified_by' => $this->session->user_id]);
           } catch (Exception $ex) {
             throw new Exception('Exam_acadamicExams_model model : Error in delete_exam_acadamicExams function - ' . $ex);
           }  
       }
      /*
        * Get exam_acadamicExams by  column name where not in particular id
      */ 
      function get_exam_acadamicExamsbyclm_name_not_id($clm_name,$clm_value,$where_cond)
      {
        try{
            $this->db->where('!=', $where_cond);
           return $this->db->get_where('exam_acadamicExams',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Exam_acadamicExams_model model : Error in get_exam_acadamicExamsbyclm_name_not_id function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join exam_acadamicExamscount 
      */ 
      function get_all_with_asso_exam_acadamicExams_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
           $this->db->select('*');
           $this->db->from('exam_acadamicExams a  ' );
              //$this->db->where($column_name, $value_id);
            $this->db->join('exam_heads b', 'b.examName=a. exHeadID','left');
              $this->db->where('a.'.$column_name, $value_id);
            $this->db->join('class c', 'c.numeric_name=a. class_id','left');
              $this->db->where('a.'.$column_name, $value_id);
            $this->db->join('academic_session d', 'd.session=a. session_id','left');
              $this->db->where('a.'.$column_name, $value_id);
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Exam_acadamicExams_model model : Error in get_all_with_asso_exam_acadamicExams_by_cat function - ' . $ex);
           }  
      }
      /*
          * Get all exam_acadamicExams_by_cat 
      */ 
      function get_all_exam_acadamicExams_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
              $this->db->order_by('', 'desc');
              $this->db->where($column_name, $value_id);
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('exam_acadamicExams')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Exam_acadamicExams_model model : Error in get_all_exam_acadamicExams_by_cat function - ' . $ex);
           }  
      } 
 }
