<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fee_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get fee by fees_id
     */
    function get_fee($class_id)
    {
        $this->db->where('class_id',$class_id);
        return $this->db->get('fees')->result_array();
//        return $this->db->get_where('fees',array('class_id'=>$class_id))->result_array();
    }

    function get_fee_headwise($session_id,$class_id,$fees_for)
    {
        $this->db->where('session_id',$session_id);
        $this->db->where('class_id',$class_id);
        $this->db->where('fees_for',$fees_for);
        $this->db->where('statusID',1);
        return $this->db->get('fees')->row()->fees_id;
//        return $this->db->get_where('fees',array('class_id'=>$class_id))->result_array();
    }

    function getFeeBySessionClass($session_id,$class_id){
        $this->db->select('*');
        $this->db->from('fees');
        $this->db->where('session_id',$session_id);
        $this->db->where('class_id',$class_id);
        $this->db->where('statusID',1);
        $query = $this->db->get()->result();
        return $query;
    }

    function getInitialFees($session_id,$class_id){
        $this->db->select('amount');
        $this->db->from('fees');
        $this->db->where('session_id',$session_id);
        $this->db->where('class_id',$class_id);
        $this->db->where('fees_for','Tuition Fees');
        $this->db->where('statusID',1);
        $query = $this->db->get()->row();
        return $query;
    }

    function get_class_all_fees($session_id,$class_id)
    {
        $this->db->where('session_id',$session_id);
        $this->db->where('class_id',$class_id);
        $this->db->where('statusID',1);

        // Execute query
    $query = $this->db->get('fees');
    
    // Log the query and result for debugging
    log_message('debug', 'SQL Query: ' . $this->db->last_query());
    $result = $query->result_array();
    log_message('debug', 'Query Result: ' . print_r($result, true));

    return $result;
      //  return $this->db->get('fees')->result_array();
//        return $this->db->get_where('fees',array('class_id'=>$class_id))->result_array();
    }
        
    /*
     * Get all fees
     */
    function get_all_fees($session_id)
    {
        $this->db->select('GROUP_CONCAT(CONCAT(f.fees_for,"-",f.amount)) fees_for,sum(f.amount) as total_fee,c.numeric_name,c.class_id');
        $this->db->from('fees f');
        $this->db->join("class c",'f.class_id=c.class_id','inner');
        $this->db->where("f.session_id",$session_id);
        $this->db->where("f.statusID",1);
        $this->db->order_by('fees_id', 'desc');
        $this->db->group_by('c.class_id');
//        $query = $this->db->get()->result_array();
//        var_dump($this->db->last_query());die;
        return $this->db->get()->result_array();
    }

    function get_all_fees_headwise($session_id,$class_id)
    {
        $this->db->select('f.fees_for,f.amount,c.numeric_name,c.class_id');
        $this->db->from('fees f');
        $this->db->join("class c",'f.class_id=c.class_id','inner');
        $this->db->where("f.session_id",$session_id);
        $this->db->where("f.class_id",$class_id);
        $this->db->where("f.statusID",1);
        $this->db->order_by('f.fees_id', 'desc');
//        $query = $this->db->get()->result_array();
//        var_dump($this->db->last_query());die;
        return $this->db->get()->result_array();
    }
        
    /*
     * function to add new fee
     */
    function add_fee($params)
    {
        $this->db->insert('fees',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update fee
     */
    function update_fee($fees_id,$params)
    {
        $this->db->where('fees_id',$fees_id);
        return $this->db->update('fees',$params);
    }
    
    /*
     * function to delete fee
     */
    function delete_fee($fees_id)
    {
        return $this->db->delete('fees',array('fees_id'=>$fees_id));
    }
    function deleteClassFees($session_id,$class_id){
        $this->db->where('session_id',$session_id);
        $this->db->where('class_id',$class_id);
        $this->db->update('fees',array('statusID'=>0,'modified_by'=> $this->session->user_id,'modified_at'=> date("Y-m-d h:i:s")));
    }
    
    function getTotalFeeByClass($class_id){
        $this->db->select('sum(amount) as total_amount');
        $this->db->from('fees');
        $this->db->where('class_id',$class_id);
        
        $query = $this->db->get();
//        var_dump($this->db->last_query());die;
        return $query->row();
    }

    function getTotalFeeByClass_coronafees($class_id){
        $this->db->select('sum(amount) as total_amount');
        $this->db->from('fees');
        $this->db->where('class_id',$class_id);
        
        $query = $this->db->get();
//        var_dump($this->db->last_query());die;
          //$corfees = 0;
        return $query->row();
    }

    function getTotalFeeByFeesType($class_id){
        $this->db->select('fees_for, amount');
        $this->db->from('fees');
        $this->db->where('class_id',$class_id);
        
        $query = $this->db->get();
//        var_dump($this->db->last_query());die;
        return $query->result_array();
    }

    function get_session_job_dates($session_id){
        $this->db->from('sys_jobdates');
        $this->db->where('session_id',$session_id);
        $this->db->order_by('sequence','asc');
        $query = $this->db->get();
        return $query->result_array();
    }

    function get_session_job_date_by_seq($session_id,$sequence){
        $this->db->from('sys_jobdates');
        $this->db->where('session_id',$session_id);
        $this->db->where('sequence',$sequence);
        $this->db->where('statusID',1);
        $this->db->order_by('sequence','asc');
        $query = $this->db->get();
        return $query->row_array();
    }

    function get_fees_job_details($session_id , $stage){
        $this->db->where('session_id',$session_id);
        $this->db->where('stage',$stage);
        $this->db->where('statusID',1);
        return $this->db->get('sys_jobdates')->row_array();
    }

    function add_fees_job_date($params)
    {
        $this->db->insert('sys_jobdates',$params);
        return $this->db->insert_id();
    }
    
    function update_fees_job_date($sysJobDatID,$params)
    {
        $this->db->where('sysJobDatID',$sysJobDatID);
        return $this->db->update('sys_jobdates',$params);
    }
}
