<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gallery_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get gallery by id
     */
    function get_gallery($id)
    {
        return $this->db->get_where('gallery',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all gallery
     */
    function get_all_gallery()
    {
         $this->db->where('show_image','1');
         $this->db->order_by('id', 'desc');
        return $this->db->get('gallery')->result_array();
    }

    function get_all_gallery_home()
    {
         $this->db->where('show_image','1');
         $this->db->order_by('id', 'desc');
        return $this->db->limit(10)->get('gallery')->result_array();
    }
    function get_home_page_gallery()
    {
        $this->db->where('show_image','1');
        $this->db->order_by('id', 'desc');
        return $this->db->get('gallery')->result_array();
    }
        
    /*
     * function to add new gallery
     */
    function add_gallery($params)
    {
        $this->db->insert('gallery',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update gallery
     */
    function update_gallery($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('gallery',$params);
    }
    
    /*
     * function to delete gallery
     */
    function delete_gallery($id)
    {
        return $this->db->delete('gallery',array('id'=>$id));
    }
}
