<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Management extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Management_model');
    } 

    /*
     * Listing of management
     */
    function index()
    {
        $data['management'] = $this->Management_model->get_all_management();
        
        $data['_view'] = 'management/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new management
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','required');
		$this->form_validation->set_rules('designation','Designation','required');
		$this->form_validation->set_rules('mobile_no','Mobile No','required');
		$this->form_validation->set_rules('image','Image','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'designation' => $this->input->post('designation'),
				'mobile_no' => $this->input->post('mobile_no'),
				'image' => $this->input->post('image'),
            );
            
            $management_id = $this->Management_model->add_management($params);
            redirect('management/index');
        }
        else
        {            
            $data['_view'] = 'management/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a management
     */
    function edit($id)
    {   
        // check if the management exists before trying to edit it
        $data['management'] = $this->Management_model->get_management($id);
        
        if(isset($data['management']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Name','required');
			$this->form_validation->set_rules('designation','Designation','required');
			$this->form_validation->set_rules('mobile_no','Mobile No','required');
			$this->form_validation->set_rules('image','Image','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'designation' => $this->input->post('designation'),
					'mobile_no' => $this->input->post('mobile_no'),
					'image' => $this->input->post('image'),
                );

                $this->Management_model->update_management($id,$params);            
                redirect('management/index');
            }
            else
            {
                $data['_view'] = 'management/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The management you are trying to edit does not exist.');
    } 

    /*
     * Deleting management
     */
    function remove($id)
    {
        $management = $this->Management_model->get_management($id);

        // check if the management exists before trying to delete it
        if(isset($management['id']))
        {
            $this->Management_model->delete_management($id);
            redirect('management/index');
        }
        else
            show_error('The management you are trying to delete does not exist.');
    }
    
}
