<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Payment_log_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get payment_log by payment_log_id
     */
    function get_payment_log($payment_log_id)
    {
        $this->db->select('p.paid_amount,p.academic_year,p.payment_id,pl.month,pl.to_month,pl.session_id,pl.payment_session,pl.reciept_no,pl.tuitionfees,pl.late_fee,(pl.tuitionfees+pl.late_fee) as total,pl.remark,pl.created_at,pl.payment_log_id,s.fullname,s.mobile_no,c.numeric_name,sec.section_name,c.class_id');
        $this->db->from('payment_log pl');
        $this->db->join('payments p','pl.payment_id=p.payment_id','inner');
        $this->db->join('student s','p.student_id=s.student_id','inner');
        $this->db->join('class c','p.class_id=c.class_id','inner');
        $this->db->join('section sec','s.section_id=sec.section_id','inner');
        $this->db->where('payment_log_id',$payment_log_id);
        return $this->db->get_where()->row();
    }
        
    /*
     * Get all payment_log
     */
    function get_all_payment_log()
    {
        
        $this->db->select('pl.*,s.fullname,c.numeric_name,sec.section_name');
        $this->db->from('payment_log pl');
        $this->db->join('payments p','pl.payment_id=p.payment_id','inner');
        $this->db->join('student s','p.student_id=s.student_id','inner');
        $this->db->join('class c','p.class_id=c.class_id','inner');
        $this->db->join('section sec','s.section_id=sec.section_id','inner');
        $this->db->where('pl.statusID',1);
        $this->db->order_by('payment_log_id', 'desc');
        //$this->db->group_by('payment_log_id');
        //var_dump($this->db->last_query());die;
        return $this->db->get()->result_array();
    }
    
    function get_all_payment_log_btween($from,$to)
    {
       
        $new_from = date('Y-m-d',strtotime(strtr($from,'/','-'))).' 00:00:00';
        $new_to = date('Y-m-d',strtotime(strtr($to,'/','-'))).' 23:59:59';
        $this->db->select('(pl.tuitionfees+pl.late_fee) as total,pl.payment_session,pl.reciept_no,pl.created_at,pl.payment_log_id,s.fullname,c.numeric_name,sec.section_name');
        $this->db->from('payment_log pl');
        $this->db->join('payments p','pl.payment_id=p.payment_id','inner');
        $this->db->join('student s','p.student_id=s.student_id','inner');
        $this->db->join('class c','s.class_id=c.class_id','inner');
        $this->db->join('section sec','c.class_id=sec.class_id','inner');
        $this->db->where('pl.created_at  BETWEEN "'.$new_from.'" AND "'.$new_to.'"');
        $this->db->where('pl.statusID',1);
        $this->db->order_by('pl.payment_log_id', 'desc');
        $this->db->group_by('pl.payment_log_id');
        return $this->db->get()->result_array();
         
    }
        
    /*
     * function to add new payment_log
     */
    function add_payment_log($params)
    {
        $this->db->insert('payment_log',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update payment_log
     */
    function update_payment_log($payment_log_id,$params)
    {
        $this->db->where('payment_log_id',$payment_log_id);
        return $this->db->update('payment_log',$params);
    }
    
    /*
     * function to delete payment_log
     */
    function delete_payment_log($payment_log_id)
    {
        $this->db->where('payment_log_id',$payment_log_id);
        return $this->db->update('payment_log',array('statusID'=>0));
    }

    function get_payment_log_for_old_receipt($payment_log_id)
    {
        return $this->db->get_where('payment_log',array('payment_log_id'=>$payment_log_id))->row_array();
    }

    function get_payment_log_payment_id($payment_id)
    {
        return $this->db->get_where('payment_log',array('payment_id'=>$payment_id))->row_array();
    }
}
