<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Student_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get student by student_id
     */
    function get_student($student_id)
    {
        $this->db->select('s.*,c.numeric_name,c.class_name,sec.section_name,s.class_id,s.section_id');
        $this->db->from('student s');
        $this->db->join('class c','s.class_id=c.class_id','inner');
        $this->db->join('section sec','s.section_id = sec.section_id','inner');
        $this->db->where('student_id',$student_id);
        $this->db->where('is_active', 1);
        
        return $this->db->get()->row_array();
    }

    function get_student_for_old_receipt($student_id)
    {
        $this->db->select('s.*,c.class_name,sec.section_name,s.class_id,s.section_id');
        $this->db->from('student s');
        $this->db->join('class c','s.class_id=c.class_id','inner');
        $this->db->join('section sec','s.section_id = sec.section_id','inner');
        $this->db->where('student_id',$student_id);
        
        return $this->db->get()->row_array();
    }
        
    /*
     * Get all student
     */
    function get_all_student()
    {
        $this->db->select('s.*,c.numeric_name,sec.section_name');
        $this->db->from('student s');
        $this->db->join('class c','s.class_id=c.class_id','inner');
        $this->db->join('section sec','s.section_id=sec.section_id','inner');
        $this->db->where('is_active',1);
        $this->db->order_by('student_id', 'desc');
        return $this->db->get()->result_array();
    }
    
    
        
    /*
     * function to add new student
     */
    function add_student($params)
    {
        $this->db->insert('student',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update student
     */
    function update_student($student_id,$params)
    {
        $this->db->where('student_id',$student_id);
        return $this->db->update('student',$params);
    }
    
    /*
     * function to delete student
     */
    function delete_student($student_id)
    {
        return $this->db->delete('student',array('student_id'=>$student_id));
    }
    
    function getStudentByClassAndSection($class,$section){
        $this->db->select('student_id,fullname,mobile_no');
        $this->db->from('student');
        $this->db->where('class_id',$class);
        $this->db->where('section_id',$section);
        $this->db->where('is_active',1);
        $query = $this->db->get();
        return $query->result_array();
    }

    function getStudentBySessionClassAndSection($session_id,$class,$section){
        $this->db->select('student_id,fullname,mobile_no,session_id,class_id,section_id');
        $this->db->from('student');
        $this->db->where('session_id',$session_id);
        $this->db->where('class_id',$class);
        $this->db->where('section_id',$section);
        $this->db->where('is_active',1);
        $query = $this->db->get();
        return $query->result_array();
    }

    function getStudentByClass($class){
        $this->db->select('student_id,fullname,mobile_no');
        $this->db->from('student');
        $this->db->where('class_id',$class);
        $this->db->where('is_active',1);
        $query = $this->db->get();
        return $query->result_array();
    }
    
    function promote_student($stud_id,$data){
        $this->db->where('student_id',$stud_id);
        $this->db->update('student',$data);
    }
    
    function getAcademicYear($stud_id){
      $this->db->select('academic_year');
      $this->db->from('student');
      $this->db->where('student_id',$stud_id);
      $query = $this->db->get();
      return $query->row();
    }
    function getrteapplicable($stud_id){
        $this->db->select('rte_applicable');
        $this->db->from('student');
        $this->db->where('student_id',$stud_id);
        $query = $this->db->get()->row();
        //print_r($query->rte_applicable);
        //die;
        return $query->rte_applicable;
        
    }
    function getStudentNoByClass($class_id){
        $this->db->select('mobile_no');
        $this->db->from('student');
        $this->db->where('class_id',$class_id);
        $query = $this->db->get();
        return $query->result_array();
    }
    
    function getStudentData($student_id){
        $this->db->select("*");
        $this->db->from("student");
        $this->db->where('student_id',$student_id);
        $query = $this->db->get();
        return $query->row();
    }
    function getStudentDataForLeaving($stud_id){
        $this->db->select('s.*,c.class_name');
        $this->db->from('student s');
        $this->db->join('class c','s.class_id=c.class_id','inner');
        $this->db->where('student_id',$stud_id);
        return $this->db->get()->row();
    }
    function getStudentDataByPaymentId($pay_id){
        $this->db->select('s.fullname,s.mobile_no,s.academic_year');
        $this->db->from('payments p');
        $this->db->join('student s','p.student_id=s.student_id','inner');
        $this->db->where('payment_id',$pay_id);
        $query = $this->db->get();
        return $query->row();
        
    }
    function getClassByNum($num){
        $this->db->select('class_id');
        $this->db->from('class');
        $this->db->where('numeric_name',$num);
        $query = $this->db->get();
        return $query->row();
    }
    function getSectionByNameAndClassId($class_id,$section){
        $this->db->select('section_id');
        $this->db->from('section');
        $this->db->where('class_id',$class_id);
        $this->db->where('section_name',$section);
        $query = $this->db->get();
        return $query->row()->section_id;
    }

    public function getSectionsByClass($class_id) {
        $this->db->where('class_id', $class_id);
        $query = $this->db->get('section'); //  table name
        return $query->result_array();
    }
    
    
    function getStudentDataForReciept($student_id){
        $this->db->select('c.numeric_name,s.section_name');
        $this->db->from('student stud');
        $this->db->join('class c','stud.class_id=c.class_id','inner');
        $this->db->join('section s','stud.section_id=s.section_id','inner');
        $this->db->where('stud.student_id',$student_id);
        return $this->db->get()->row();
    }
    function getMaxPaymentLogId(){
        $this->db->select('max(payment_log_id) as maxid');
        $this->db->from('payment_log');
        $max = $this->db->get()->row();
        return $max->maxid;
    }
    
    function getActiveStudent(){
        $this->db->select('mobile_no');
        $this->db->from('student');
        $this->db->where('is_active',1);
        return $this->db->get()->result_array();
    }

    function getStudentBySessionAndClass($session_id,$class_id){
        $this->db->select('*');
        $this->db->from('student');
        $this->db->where('class_id',$class_id);
        $this->db->where('session_id',$session_id);
        $this->db->where('is_active',1);
        $query = $this->db->get();
        return $query->result_array();
    }
}
